changelog:
  categories:
    - title: Enhancements 🛠
      labels:
        - enhancement

    - title: Fixed Bugs 🐛
      labels:
        - bug

    - title: Documentation 📄
      labels:
        - documentation

    - title: Other Changes 🤖
      labels:
        - "*"