apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  annotations:
    cni.projectcalico.org/ipAddrs: 192.168.255.1
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Always