---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1alpha1-cassandra
  failurePolicy: Fail
  name: vcassandra.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cassandras
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1alpha1-kafka
  failurePolicy: Fail
  name: mkafka.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1alpha1-opensearch
  failurePolicy: Fail
  name: mopensearch.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1alpha1-postgresql
  failurePolicy: Fail
  name: mpostgresql.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - postgresqls
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1alpha1-awssecuritygroupfirewallrule
  failurePolicy: Fail
  name: vawssecuritygroupfirewallrule.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awssecuritygroupfirewallrules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1alpha1-awsvpcpeering
  failurePolicy: Fail
  name: vawsvpcpeering.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsvpcpeerings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1alpha1-clusternetworkfirewallrule
  failurePolicy: Fail
  name: vclusternetworkfirewallrule.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusternetworkfirewallrules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1alpha1-cassandra
  failurePolicy: Fail
  name: vcassandra.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cassandras
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1alpha1-kafka
  failurePolicy: Fail
  name: vkafka.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1alpha1-opensearch
  failurePolicy: Fail
  name: vopensearch.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1alpha1-postgresql
  failurePolicy: Fail
  name: vpostgresql.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - postgresqls
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1alpha1-redis
  failurePolicy: Fail
  name: vredis.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redis
  sideEffects: None
