---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusterresources-instaclustr-com-v1beta1-awsencryptionkey
  failurePolicy: Fail
  name: mawsencryptionkey.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsencryptionkeys
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusterresources-instaclustr-com-v1beta1-awssecuritygroupfirewallrule
  failurePolicy: Fail
  name: mawssecuritygroupfirewallrule.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awssecuritygroupfirewallrules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusterresources-instaclustr-com-v1beta1-awsvpcpeering
  failurePolicy: Fail
  name: mawsvpcpeering.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsvpcpeerings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusterresources-instaclustr-com-v1beta1-azurevnetpeering
  failurePolicy: Fail
  name: mazurevnetpeering.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azurevnetpeerings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusterresources-instaclustr-com-v1beta1-clusternetworkfirewallrule
  failurePolicy: Fail
  name: mclusternetworkfirewallrule.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusternetworkfirewallrules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusterresources-instaclustr-com-v1beta1-exclusionwindow
  failurePolicy: Fail
  name: mexclusionwindow.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - exclusionwindows
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusterresources-instaclustr-com-v1beta1-gcpvpcpeering
  failurePolicy: Fail
  name: mgcpvpcpeering.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gcpvpcpeerings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1beta1-cadence
  failurePolicy: Fail
  name: mcadence.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cadences
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1beta1-cassandra
  failurePolicy: Fail
  name: mcassandra.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cassandras
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1beta1-kafka
  failurePolicy: Fail
  name: mkafka.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1beta1-kafkaconnect
  failurePolicy: Fail
  name: mkafkaconnect.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkaconnects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1beta1-opensearch
  failurePolicy: Fail
  name: mopensearch.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1beta1-postgresql
  failurePolicy: Fail
  name: mpostgresql.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - postgresqls
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1beta1-redis
  failurePolicy: Fail
  name: mredis.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-instaclustr-com-v1beta1-zookeeper
  failurePolicy: Fail
  name: mzookeeper.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - zookeepers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kafkamanagement-instaclustr-com-v1beta1-kafkaacl
  failurePolicy: Fail
  name: mkafkaacl.kb.io
  rules:
  - apiGroups:
    - kafkamanagement.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkaacls
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kafkamanagement-instaclustr-com-v1beta1-kafkauser
  failurePolicy: Fail
  name: mkafkauser.kb.io
  rules:
  - apiGroups:
    - kafkamanagement.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkausers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kafkamanagement-instaclustr-com-v1beta1-mirror
  failurePolicy: Fail
  name: mmirror.kb.io
  rules:
  - apiGroups:
    - kafkamanagement.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mirrors
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kafkamanagement-instaclustr-com-v1beta1-topic
  failurePolicy: Fail
  name: mtopic.kb.io
  rules:
  - apiGroups:
    - kafkamanagement.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - topics
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-awsencryptionkey
  failurePolicy: Fail
  name: vawsencryptionkey.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsencryptionkeys
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-awsendpointserviceprincipal
  failurePolicy: Fail
  name: vawsendpointserviceprincipal.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsendpointserviceprincipals
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-awssecuritygroupfirewallrule
  failurePolicy: Fail
  name: vawssecuritygroupfirewallrule.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awssecuritygroupfirewallrules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-awsvpcpeering
  failurePolicy: Fail
  name: vawsvpcpeering.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsvpcpeerings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-azurevnetpeering
  failurePolicy: Fail
  name: vazurevnetpeering.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azurevnetpeerings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-cassandrauser
  failurePolicy: Fail
  name: vcassandrauser.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cassandrausers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-clusternetworkfirewallrule
  failurePolicy: Fail
  name: vclusternetworkfirewallrule.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusternetworkfirewallrules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-exclusionwindow
  failurePolicy: Fail
  name: vexclusionwindow.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - exclusionwindows
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-gcpvpcpeering
  failurePolicy: Fail
  name: vgcpvpcpeering.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gcpvpcpeerings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-maintenanceevents
  failurePolicy: Fail
  name: vmaintenanceevents.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - maintenanceevents
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-nodereload
  failurePolicy: Fail
  name: vnodereload.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodereloads
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-opensearchuser
  failurePolicy: Fail
  name: vopensearchuser.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchusers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusterresources-instaclustr-com-v1beta1-redisuser
  failurePolicy: Fail
  name: vredisuser.kb.io
  rules:
  - apiGroups:
    - clusterresources.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redisusers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1beta1-cadence
  failurePolicy: Fail
  name: vcadence.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cadences
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1beta1-cassandra
  failurePolicy: Fail
  name: vcassandra.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cassandras
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1beta1-kafka
  failurePolicy: Fail
  name: vkafka.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1beta1-kafkaconnect
  failurePolicy: Fail
  name: vkafkaconnect.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkaconnects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1beta1-opensearch
  failurePolicy: Fail
  name: vopensearch.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1beta1-postgresql
  failurePolicy: Fail
  name: vpostgresql.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - postgresqls
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1beta1-redis
  failurePolicy: Fail
  name: vredis.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-instaclustr-com-v1beta1-zookeeper
  failurePolicy: Fail
  name: vzookeeper.kb.io
  rules:
  - apiGroups:
    - clusters.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - zookeepers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kafkamanagement-instaclustr-com-v1beta1-kafkaacl
  failurePolicy: Fail
  name: vkafkaacl.kb.io
  rules:
  - apiGroups:
    - kafkamanagement.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkaacls
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kafkamanagement-instaclustr-com-v1beta1-kafkauser
  failurePolicy: Fail
  name: vkafkauser.kb.io
  rules:
  - apiGroups:
    - kafkamanagement.instaclustr.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkausers
  sideEffects: None
