/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// KafkaTopicV2ApiService is a service that implements the logic for the KafkaTopicV2ApiServicer
// This service should implement the business logic for every endpoint for the KafkaTopicV2Api API.
// Include any external packages or services that will be required by this service.
type KafkaTopicV2ApiService struct {
}

// NewKafkaTopicV2ApiService creates a default api service
func NewKafkaTopicV2ApiService() KafkaTopicV2ApiServicer {
	return &KafkaTopicV2ApiService{}
}

// ClusterManagementV2OperationsApplicationsKafkaTopicsV2KafkaTopicIdModifyConfigsV2Put - Update Kafka topic configs
func (s *KafkaTopicV2ApiService) ClusterManagementV2OperationsApplicationsKafkaTopicsV2KafkaTopicIdModifyConfigsV2Put(ctx context.Context, kafkaTopicId string, body KafkaTopicConfigsV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2OperationsApplicationsKafkaTopicsV2KafkaTopicIdModifyConfigsV2Put with the required logic for this service method.
	// Add api_kafka_topic_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, KafkaTopicV2{}) or use other options such as http.Ok ...
	//return Response(200, KafkaTopicV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2OperationsApplicationsKafkaTopicsV2KafkaTopicIdModifyConfigsV2Put method not implemented")
}

// ClusterManagementV2ResourcesApplicationsKafkaTopicsV2KafkaTopicIdDelete - Delete the kafka topic
func (s *KafkaTopicV2ApiService) ClusterManagementV2ResourcesApplicationsKafkaTopicsV2KafkaTopicIdDelete(ctx context.Context, kafkaTopicId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsKafkaTopicsV2KafkaTopicIdDelete with the required logic for this service method.
	// Add api_kafka_topic_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesApplicationsKafkaTopicsV2KafkaTopicIdDelete method not implemented")
}

// ClusterManagementV2ResourcesApplicationsKafkaTopicsV2KafkaTopicIdGet - Get Kafka Topic details
func (s *KafkaTopicV2ApiService) ClusterManagementV2ResourcesApplicationsKafkaTopicsV2KafkaTopicIdGet(ctx context.Context, kafkaTopicId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsKafkaTopicsV2KafkaTopicIdGet with the required logic for this service method.
	// Add api_kafka_topic_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, KafkaTopicV2{}) or use other options such as http.Ok ...
	//return Response(200, KafkaTopicV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesApplicationsKafkaTopicsV2KafkaTopicIdGet method not implemented")
}

// ClusterManagementV2ResourcesApplicationsKafkaTopicsV2Post - Create a Kafka Topic
func (s *KafkaTopicV2ApiService) ClusterManagementV2ResourcesApplicationsKafkaTopicsV2Post(ctx context.Context, body KafkaTopicV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsKafkaTopicsV2Post with the required logic for this service method.
	// Add api_kafka_topic_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(202, KafkaTopicV2{}) or use other options such as http.Ok ...
	//return Response(202, KafkaTopicV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesApplicationsKafkaTopicsV2Post method not implemented")
}
