/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// CadenceClusterV2ApiService is a service that implements the logic for the CadenceClusterV2ApiServicer
// This service should implement the business logic for every endpoint for the CadenceClusterV2Api API.
// Include any external packages or services that will be required by this service.
type CadenceClusterV2ApiService struct {
}

// NewCadenceClusterV2ApiService creates a default api service
func NewCadenceClusterV2ApiService() CadenceClusterV2ApiServicer {
	return &CadenceClusterV2ApiService{}
}

// ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdDelete - Delete cluster
func (s *CadenceClusterV2ApiService) ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdDelete(ctx context.Context, clusterId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdDelete with the required logic for this service method.
	// Add api_cadence_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdDelete method not implemented")
}

// ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdGet - Get Cadence cluster details.
func (s *CadenceClusterV2ApiService) ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdGet(ctx context.Context, clusterId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdGet with the required logic for this service method.
	// Add api_cadence_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, CadenceClusterV2{}) or use other options such as http.Ok ...
	//return Response(200, CadenceClusterV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdGet method not implemented")
}

// ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdPut - Update a Cadence cluster
func (s *CadenceClusterV2ApiService) ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdPut(ctx context.Context, clusterId string, body CadenceClusterUpdateV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdPut with the required logic for this service method.
	// Add api_cadence_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(202, CadenceClusterV2{}) or use other options such as http.Ok ...
	//return Response(202, CadenceClusterV2{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorListResponseV2{}) or use other options such as http.Ok ...
	//return Response(404, ErrorListResponseV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdPut method not implemented")
}

// ClusterManagementV2ResourcesApplicationsCadenceClustersV2Post - Create a Cadence cluster
func (s *CadenceClusterV2ApiService) ClusterManagementV2ResourcesApplicationsCadenceClustersV2Post(ctx context.Context, body CadenceClusterV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsCadenceClustersV2Post with the required logic for this service method.
	// Add api_cadence_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(202, CadenceClusterV2{}) or use other options such as http.Ok ...
	//return Response(202, CadenceClusterV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesApplicationsCadenceClustersV2Post method not implemented")
}
