/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"
)

// TerraformDocumentationV2ApiController binds http requests to an api service and writes the service results to the http response
type TerraformDocumentationV2ApiController struct {
	service      TerraformDocumentationV2ApiServicer
	errorHandler ErrorHandler
}

// TerraformDocumentationV2ApiOption for how the controller is set up.
type TerraformDocumentationV2ApiOption func(*TerraformDocumentationV2ApiController)

// WithTerraformDocumentationV2ApiErrorHandler inject ErrorHandler into controller
func WithTerraformDocumentationV2ApiErrorHandler(h ErrorHandler) TerraformDocumentationV2ApiOption {
	return func(c *TerraformDocumentationV2ApiController) {
		c.errorHandler = h
	}
}

// NewTerraformDocumentationV2ApiController creates a default api controller
func NewTerraformDocumentationV2ApiController(s TerraformDocumentationV2ApiServicer, opts ...TerraformDocumentationV2ApiOption) Router {
	controller := &TerraformDocumentationV2ApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the TerraformDocumentationV2ApiController
func (c *TerraformDocumentationV2ApiController) Routes() Routes {
	return Routes{
		{
			"ClusterManagementV2OperationsGenerateTerraformDocumentationV2Get",
			strings.ToUpper("Get"),
			"/cluster-management/v2/operations/generate-terraform-documentation/v2",
			c.ClusterManagementV2OperationsGenerateTerraformDocumentationV2Get,
		},
	}
}

// ClusterManagementV2OperationsGenerateTerraformDocumentationV2Get - Download Terraform documentation
func (c *TerraformDocumentationV2ApiController) ClusterManagementV2OperationsGenerateTerraformDocumentationV2Get(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.ClusterManagementV2OperationsGenerateTerraformDocumentationV2Get(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
