/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
)

// PostgresqlClusterV2ApiService is a service that implements the logic for the PostgresqlClusterV2ApiServicer
// This service should implement the business logic for every endpoint for the PostgresqlClusterV2Api API.
// Include any external packages or services that will be required by this service.
type PostgresqlClusterV2ApiService struct {
	MockPostgresqlCluster *PostgresqlClusterV2
}

// NewPostgresqlClusterV2ApiService creates a default api service
func NewPostgresqlClusterV2ApiService() PostgresqlClusterV2ApiServicer {
	return &PostgresqlClusterV2ApiService{}
}

// ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdDelete - Delete cluster
func (s *PostgresqlClusterV2ApiService) ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdDelete(ctx context.Context, clusterId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdDelete with the required logic for this service method.
	// Add api_postgresql_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	s.MockPostgresqlCluster = nil
	return Response(204, nil), nil
}

// ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdGet - Get Postgresql cluster details.
func (s *PostgresqlClusterV2ApiService) ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdGet(ctx context.Context, clusterId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdGet with the required logic for this service method.
	// Add api_postgresql_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	if s.MockPostgresqlCluster != nil {
		s.MockPostgresqlCluster.Status = RUNNING
		s.MockPostgresqlCluster.CurrentClusterOperationStatus = NO_OPERATION
	} else {
		return Response(404, nil), nil
	}

	return Response(200, s.MockPostgresqlCluster), nil
}

// ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdPut - Update PostgreSQL cluster details
func (s *PostgresqlClusterV2ApiService) ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdPut(ctx context.Context, clusterId string, body PostgresqlClusterUpdateV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdPut with the required logic for this service method.
	// Add api_postgresql_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	newNode := []NodeDetailsV2{{
		Rack:          "us-east-1a",
		NodeSize:      body.DataCentres[0].NodeSize,
		PublicAddress: "54.146.160.89",
	}}

	s.MockPostgresqlCluster.DataCentres[0].Nodes = newNode

	return Response(202, nil), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorListResponseV2{}) or use other options such as http.Ok ...
	//return Response(404, ErrorListResponseV2{}), nil
}

// ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2Post - Create a Postgresql cluster.
func (s *PostgresqlClusterV2ApiService) ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2Post(ctx context.Context, body PostgresqlClusterV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2Post with the required logic for this service method.
	// Add api_postgresql_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	s.MockPostgresqlCluster = &body
	s.MockPostgresqlCluster.Id = CreatedID
	return Response(202, s.MockPostgresqlCluster), nil
}
