/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// ClusterExclusionWindowV2APIService is a service that implements the logic for the ClusterExclusionWindowV2APIServicer
// This service should implement the business logic for every endpoint for the ClusterExclusionWindowV2API API.
// Include any external packages or services that will be required by this service.
type ClusterExclusionWindowV2APIService struct {
}

// NewClusterExclusionWindowV2APIService creates a default api service
func NewClusterExclusionWindowV2APIService() ClusterExclusionWindowV2APIServicer {
	return &ClusterExclusionWindowV2APIService{}
}

// ClusterManagementV2DataSourcesClusterClusterIdExclusionWindowsV2Get - List cluster exclusion windows
func (s *ClusterExclusionWindowV2APIService) ClusterManagementV2DataSourcesClusterClusterIdExclusionWindowsV2Get(ctx context.Context, clusterId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2DataSourcesClusterClusterIdExclusionWindowsV2Get with the required logic for this service method.
	// Add api_cluster_exclusion_window_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []ClusterExclusionWindowsV2{}) or use other options such as http.Ok ...
	// return Response(200, []ClusterExclusionWindowsV2{}), nil

	// TODO: Uncomment the next line to return response Response(400, ErrorListResponseV2{}) or use other options such as http.Ok ...
	// return Response(400, ErrorListResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(401, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(401, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(404, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(415, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(415, ErrorResponseV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2DataSourcesClusterClusterIdExclusionWindowsV2Get method not implemented")
}

// ClusterManagementV2ResourcesExclusionWindowsV2Post - Create cluster exclusion window
func (s *ClusterExclusionWindowV2APIService) ClusterManagementV2ResourcesExclusionWindowsV2Post(ctx context.Context, clusterExclusionWindowV2 ClusterExclusionWindowV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesExclusionWindowsV2Post with the required logic for this service method.
	// Add api_cluster_exclusion_window_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(202, ClusterExclusionWindowV2{}) or use other options such as http.Ok ...
	// return Response(202, ClusterExclusionWindowV2{}), nil

	// TODO: Uncomment the next line to return response Response(400, ErrorListResponseV2{}) or use other options such as http.Ok ...
	// return Response(400, ErrorListResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(401, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(401, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(404, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(415, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(415, ErrorResponseV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesExclusionWindowsV2Post method not implemented")
}

// ClusterManagementV2ResourcesExclusionWindowsV2WindowIdDelete - Delete cluster exclusion window
func (s *ClusterExclusionWindowV2APIService) ClusterManagementV2ResourcesExclusionWindowsV2WindowIdDelete(ctx context.Context, windowId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesExclusionWindowsV2WindowIdDelete with the required logic for this service method.
	// Add api_cluster_exclusion_window_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(400, ErrorListResponseV2{}) or use other options such as http.Ok ...
	// return Response(400, ErrorListResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(401, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(401, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(404, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(415, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(415, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(429, {}) or use other options such as http.Ok ...
	// return Response(429, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesExclusionWindowsV2WindowIdDelete method not implemented")
}

// ClusterManagementV2ResourcesExclusionWindowsV2WindowIdGet - Get cluster exclusion window details
func (s *ClusterExclusionWindowV2APIService) ClusterManagementV2ResourcesExclusionWindowsV2WindowIdGet(ctx context.Context, windowId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesExclusionWindowsV2WindowIdGet with the required logic for this service method.
	// Add api_cluster_exclusion_window_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ClusterExclusionWindowV2{}) or use other options such as http.Ok ...
	// return Response(200, ClusterExclusionWindowV2{}), nil

	// TODO: Uncomment the next line to return response Response(400, ErrorListResponseV2{}) or use other options such as http.Ok ...
	// return Response(400, ErrorListResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(401, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(401, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(404, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(415, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(415, ErrorResponseV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesExclusionWindowsV2WindowIdGet method not implemented")
}
