/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// ApacheKafkaConnectMirrorV2APIController binds http requests to an api service and writes the service results to the http response
type ApacheKafkaConnectMirrorV2APIController struct {
	service      ApacheKafkaConnectMirrorV2APIServicer
	errorHandler ErrorHandler
}

// ApacheKafkaConnectMirrorV2APIOption for how the controller is set up.
type ApacheKafkaConnectMirrorV2APIOption func(*ApacheKafkaConnectMirrorV2APIController)

// WithApacheKafkaConnectMirrorV2APIErrorHandler inject ErrorHandler into controller
func WithApacheKafkaConnectMirrorV2APIErrorHandler(h ErrorHandler) ApacheKafkaConnectMirrorV2APIOption {
	return func(c *ApacheKafkaConnectMirrorV2APIController) {
		c.errorHandler = h
	}
}

// NewApacheKafkaConnectMirrorV2APIController creates a default api controller
func NewApacheKafkaConnectMirrorV2APIController(s ApacheKafkaConnectMirrorV2APIServicer, opts ...ApacheKafkaConnectMirrorV2APIOption) Router {
	controller := &ApacheKafkaConnectMirrorV2APIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ApacheKafkaConnectMirrorV2APIController
func (c *ApacheKafkaConnectMirrorV2APIController) Routes() Routes {
	return Routes{
		"ClusterManagementV2DataSourcesKafkaConnectClusterClusterIdMirrorsV2Get": Route{
			strings.ToUpper("Get"),
			"/cluster-management/v2/data-sources/kafka_connect_cluster/{clusterId}/mirrors/v2/",
			c.ClusterManagementV2DataSourcesKafkaConnectClusterClusterIdMirrorsV2Get,
		},
		"ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdDelete": Route{
			strings.ToUpper("Delete"),
			"/cluster-management/v2/resources/applications/kafka_connect/mirrors/v2/{mirrorId}",
			c.ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdDelete,
		},
		"ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdGet": Route{
			strings.ToUpper("Get"),
			"/cluster-management/v2/resources/applications/kafka_connect/mirrors/v2/{mirrorId}",
			c.ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdGet,
		},
		"ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdPut": Route{
			strings.ToUpper("Put"),
			"/cluster-management/v2/resources/applications/kafka_connect/mirrors/v2/{mirrorId}",
			c.ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdPut,
		},
		"ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2Post": Route{
			strings.ToUpper("Post"),
			"/cluster-management/v2/resources/applications/kafka_connect/mirrors/v2",
			c.ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2Post,
		},
	}
}

// ClusterManagementV2DataSourcesKafkaConnectClusterClusterIdMirrorsV2Get - List all Kafka connect mirrors.
func (c *ApacheKafkaConnectMirrorV2APIController) ClusterManagementV2DataSourcesKafkaConnectClusterClusterIdMirrorsV2Get(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	clusterIdParam := params["clusterId"]
	result, err := c.service.ClusterManagementV2DataSourcesKafkaConnectClusterClusterIdMirrorsV2Get(r.Context(), clusterIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdDelete - Delete a Kafka Connect Mirror
func (c *ApacheKafkaConnectMirrorV2APIController) ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdDelete(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	mirrorIdParam := params["mirrorId"]
	result, err := c.service.ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdDelete(r.Context(), mirrorIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdGet - Get the details of a kafka connect mirror
func (c *ApacheKafkaConnectMirrorV2APIController) ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	mirrorIdParam := params["mirrorId"]
	result, err := c.service.ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdGet(r.Context(), mirrorIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdPut - Update a Kafka Connect mirror.
func (c *ApacheKafkaConnectMirrorV2APIController) ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdPut(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	mirrorIdParam := params["mirrorId"]
	kafkaConnectMirrorUpdateV2Param := KafkaConnectMirrorUpdateV2{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&kafkaConnectMirrorUpdateV2Param); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertKafkaConnectMirrorUpdateV2Required(kafkaConnectMirrorUpdateV2Param); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertKafkaConnectMirrorUpdateV2Constraints(kafkaConnectMirrorUpdateV2Param); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2MirrorIdPut(r.Context(), mirrorIdParam, kafkaConnectMirrorUpdateV2Param)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2Post - Create a Kafka Connect mirror
func (c *ApacheKafkaConnectMirrorV2APIController) ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2Post(w http.ResponseWriter, r *http.Request) {
	kafkaConnectMirrorV2Param := KafkaConnectMirrorV2{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&kafkaConnectMirrorV2Param); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertKafkaConnectMirrorV2Required(kafkaConnectMirrorV2Param); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertKafkaConnectMirrorV2Constraints(kafkaConnectMirrorV2Param); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ClusterManagementV2ResourcesApplicationsKafkaConnectMirrorsV2Post(r.Context(), kafkaConnectMirrorV2Param)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
