/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// PostgreSQLUserV2APIService is a service that implements the logic for the PostgreSQLUserV2APIServicer
// This service should implement the business logic for every endpoint for the PostgreSQLUserV2API API.
// Include any external packages or services that will be required by this service.
type PostgreSQLUserV2APIService struct {
}

// NewPostgreSQLUserV2APIService creates a default api service
func NewPostgreSQLUserV2APIService() PostgreSQLUserV2APIServicer {
	return &PostgreSQLUserV2APIService{}
}

// ClusterManagementV2OperationsApplicationsPostgresqlClustersV2ClusterIdUpdateDefaultUserPasswordPut - Update the default PostgreSQL user password.
func (s *PostgreSQLUserV2APIService) ClusterManagementV2OperationsApplicationsPostgresqlClustersV2ClusterIdUpdateDefaultUserPasswordPut(ctx context.Context, clusterId string, postgresqlUserSummary PostgresqlUserSummary) (ImplResponse, error) {
	// TODO - update ClusterManagementV2OperationsApplicationsPostgresqlClustersV2ClusterIdUpdateDefaultUserPasswordPut with the required logic for this service method.
	// Add api_postgre_sql_user_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(202, PostgresqlUserSummary{}) or use other options such as http.Ok ...
	// return Response(202, PostgresqlUserSummary{}), nil

	// TODO: Uncomment the next line to return response Response(404, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(404, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(503, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(503, ErrorResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(504, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(504, ErrorResponseV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2OperationsApplicationsPostgresqlClustersV2ClusterIdUpdateDefaultUserPasswordPut method not implemented")
}
