/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// RedisUserV2APIController binds http requests to an api service and writes the service results to the http response
type RedisUserV2APIController struct {
	service      RedisUserV2APIServicer
	errorHandler ErrorHandler
}

// RedisUserV2APIOption for how the controller is set up.
type RedisUserV2APIOption func(*RedisUserV2APIController)

// WithRedisUserV2APIErrorHandler inject ErrorHandler into controller
func WithRedisUserV2APIErrorHandler(h ErrorHandler) RedisUserV2APIOption {
	return func(c *RedisUserV2APIController) {
		c.errorHandler = h
	}
}

// NewRedisUserV2APIController creates a default api controller
func NewRedisUserV2APIController(s RedisUserV2APIServicer, opts ...RedisUserV2APIOption) Router {
	controller := &RedisUserV2APIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the RedisUserV2APIController
func (c *RedisUserV2APIController) Routes() Routes {
	return Routes{
		"ClusterManagementV2DataSourcesRedisClusterClusterIdUsersV2Get": Route{
			strings.ToUpper("Get"),
			"/cluster-management/v2/data-sources/redis_cluster/{clusterId}/users/v2/",
			c.ClusterManagementV2DataSourcesRedisClusterClusterIdUsersV2Get,
		},
		"ClusterManagementV2ResourcesApplicationsRedisUsersV2Post": Route{
			strings.ToUpper("Post"),
			"/cluster-management/v2/resources/applications/redis/users/v2/",
			c.ClusterManagementV2ResourcesApplicationsRedisUsersV2Post,
		},
		"ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdDelete": Route{
			strings.ToUpper("Delete"),
			"/cluster-management/v2/resources/applications/redis/users/v2/{redisUserId}/",
			c.ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdDelete,
		},
		"ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdGet": Route{
			strings.ToUpper("Get"),
			"/cluster-management/v2/resources/applications/redis/users/v2/{redisUserId}/",
			c.ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdGet,
		},
		"ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdPut": Route{
			strings.ToUpper("Put"),
			"/cluster-management/v2/resources/applications/redis/users/v2/{redisUserId}/",
			c.ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdPut,
		},
	}
}

// ClusterManagementV2DataSourcesRedisClusterClusterIdUsersV2Get - List all Redis users.
func (c *RedisUserV2APIController) ClusterManagementV2DataSourcesRedisClusterClusterIdUsersV2Get(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	clusterIdParam := params["clusterId"]
	result, err := c.service.ClusterManagementV2DataSourcesRedisClusterClusterIdUsersV2Get(r.Context(), clusterIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ClusterManagementV2ResourcesApplicationsRedisUsersV2Post - Create a Redis User.
func (c *RedisUserV2APIController) ClusterManagementV2ResourcesApplicationsRedisUsersV2Post(w http.ResponseWriter, r *http.Request) {
	redisUserV2Param := RedisUserV2{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&redisUserV2Param); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertRedisUserV2Required(redisUserV2Param); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertRedisUserV2Constraints(redisUserV2Param); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ClusterManagementV2ResourcesApplicationsRedisUsersV2Post(r.Context(), redisUserV2Param)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdDelete - Delete a Redis user
func (c *RedisUserV2APIController) ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdDelete(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	redisUserIdParam := params["redisUserId"]
	result, err := c.service.ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdDelete(r.Context(), redisUserIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdGet - Get Redis User details.
func (c *RedisUserV2APIController) ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	redisUserIdParam := params["redisUserId"]
	result, err := c.service.ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdGet(r.Context(), redisUserIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdPut - Update Redis user password
func (c *RedisUserV2APIController) ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdPut(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	redisUserIdParam := params["redisUserId"]
	redisUserPasswordV2Param := RedisUserPasswordV2{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&redisUserPasswordV2Param); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertRedisUserPasswordV2Required(redisUserPasswordV2Param); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertRedisUserPasswordV2Constraints(redisUserPasswordV2Param); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ClusterManagementV2ResourcesApplicationsRedisUsersV2RedisUserIdPut(r.Context(), redisUserIdParam, redisUserPasswordV2Param)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
