/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// AccountClusterListV2APIService is a service that implements the logic for the AccountClusterListV2APIServicer
// This service should implement the business logic for every endpoint for the AccountClusterListV2API API.
// Include any external packages or services that will be required by this service.
type AccountClusterListV2APIService struct {
}

// NewAccountClusterListV2APIService creates a default api service
func NewAccountClusterListV2APIService() AccountClusterListV2APIServicer {
	return &AccountClusterListV2APIService{}
}

// ClusterManagementV2DataSourcesClustersV2Get - Get Active Cluster IDs
func (s *AccountClusterListV2APIService) ClusterManagementV2DataSourcesClustersV2Get(ctx context.Context) (ImplResponse, error) {
	// TODO - update ClusterManagementV2DataSourcesClustersV2Get with the required logic for this service method.
	// Add api_account_cluster_list_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []AccountClustersV2{}) or use other options such as http.Ok ...
	// return Response(200, []AccountClustersV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2DataSourcesClustersV2Get method not implemented")
}
