/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// GCPVPCPeerV2ApiController binds http requests to an api service and writes the service results to the http response
type GCPVPCPeerV2ApiController struct {
	service      GCPVPCPeerV2ApiServicer
	errorHandler ErrorHandler
}

// GCPVPCPeerV2ApiOption for how the controller is set up.
type GCPVPCPeerV2ApiOption func(*GCPVPCPeerV2ApiController)

// WithGCPVPCPeerV2ApiErrorHandler inject ErrorHandler into controller
func WithGCPVPCPeerV2ApiErrorHandler(h ErrorHandler) GCPVPCPeerV2ApiOption {
	return func(c *GCPVPCPeerV2ApiController) {
		c.errorHandler = h
	}
}

// NewGCPVPCPeerV2ApiController creates a default api controller
func NewGCPVPCPeerV2ApiController(s GCPVPCPeerV2ApiServicer, opts ...GCPVPCPeerV2ApiOption) Router {
	controller := &GCPVPCPeerV2ApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the GCPVPCPeerV2ApiController
func (c *GCPVPCPeerV2ApiController) Routes() Routes {
	return Routes{
		{
			"ClusterManagementV2DataSourcesProvidersGcpVpcPeersV2Get",
			strings.ToUpper("Get"),
			"/cluster-management/v2/data-sources/providers/gcp/vpc-peers/v2",
			c.ClusterManagementV2DataSourcesProvidersGcpVpcPeersV2Get,
		},
		{
			"ClusterManagementV2ResourcesProvidersGcpVpcPeersV2Post",
			strings.ToUpper("Post"),
			"/cluster-management/v2/resources/providers/gcp/vpc-peers/v2",
			c.ClusterManagementV2ResourcesProvidersGcpVpcPeersV2Post,
		},
		{
			"ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdDelete",
			strings.ToUpper("Delete"),
			"/cluster-management/v2/resources/providers/gcp/vpc-peers/v2/{vpcPeerId}",
			c.ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdDelete,
		},
		{
			"ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdGet",
			strings.ToUpper("Get"),
			"/cluster-management/v2/resources/providers/gcp/vpc-peers/v2/{vpcPeerId}",
			c.ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdGet,
		},
	}
}

// ClusterManagementV2DataSourcesProvidersGcpVpcPeersV2Get - List all GCP VPC Peering requests
func (c *GCPVPCPeerV2ApiController) ClusterManagementV2DataSourcesProvidersGcpVpcPeersV2Get(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.ClusterManagementV2DataSourcesProvidersGcpVpcPeersV2Get(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ClusterManagementV2ResourcesProvidersGcpVpcPeersV2Post - Create GCP VPC Peering Request
func (c *GCPVPCPeerV2ApiController) ClusterManagementV2ResourcesProvidersGcpVpcPeersV2Post(w http.ResponseWriter, r *http.Request) {
	bodyParam := GcpVpcPeerV2{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bodyParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertGcpVpcPeerV2Required(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ClusterManagementV2ResourcesProvidersGcpVpcPeersV2Post(r.Context(), bodyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdDelete - Delete GCP VPC Peering Connection
func (c *GCPVPCPeerV2ApiController) ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdDelete(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	vpcPeerIdParam := params["vpcPeerId"]

	result, err := c.service.ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdDelete(r.Context(), vpcPeerIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdGet - Get GCP VPC Peering Connection info
func (c *GCPVPCPeerV2ApiController) ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	vpcPeerIdParam := params["vpcPeerId"]

	result, err := c.service.ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdGet(r.Context(), vpcPeerIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
