/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
	"sync"

	"github.com/google/uuid"
)

// ClusterNetworkFirewallRuleV2APIService is a service that implements the logic for the ClusterNetworkFirewallRuleV2APIServicer
// This service should implement the business logic for every endpoint for the ClusterNetworkFirewallRuleV2API API.
// Include any external packages or services that will be required by this service.
type ClusterNetworkFirewallRuleV2APIService struct {
	mu    sync.RWMutex
	rules map[string]*ClusterNetworkFirewallRuleV2
}

// NewClusterNetworkFirewallRuleV2APIService creates a default api service
func NewClusterNetworkFirewallRuleV2APIService() ClusterNetworkFirewallRuleV2APIServicer {
	return &ClusterNetworkFirewallRuleV2APIService{rules: map[string]*ClusterNetworkFirewallRuleV2{}}
}

// ClusterManagementV2DataSourcesClusterClusterIdNetworkFirewallRulesV2Get - List all cluster network firewall rules
func (s *ClusterNetworkFirewallRuleV2APIService) ClusterManagementV2DataSourcesClusterClusterIdNetworkFirewallRulesV2Get(ctx context.Context, clusterId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2DataSourcesClusterClusterIdNetworkFirewallRulesV2Get with the required logic for this service method.
	// Add api_cluster_network_firewall_rule_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []ClusterNetworkFirewallRulesV2{}) or use other options such as http.Ok ...
	// return Response(200, []ClusterNetworkFirewallRulesV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2DataSourcesClusterClusterIdNetworkFirewallRulesV2Get method not implemented")
}

// ClusterManagementV2ResourcesNetworkFirewallRulesV2FirewallRuleIdDelete - Delete cluster network firewall rule
func (s *ClusterNetworkFirewallRuleV2APIService) ClusterManagementV2ResourcesNetworkFirewallRulesV2FirewallRuleIdDelete(ctx context.Context, firewallRuleId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesNetworkFirewallRulesV2FirewallRuleIdDelete with the required logic for this service method.
	// Add api_cluster_network_firewall_rule_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, ErrorListResponseV2{}) or use other options such as http.Ok ...
	// return Response(404, ErrorListResponseV2{}), nil

	s.mu.Lock()
	defer s.mu.Unlock()

	_, exists := s.rules[firewallRuleId]
	if !exists {
		return Response(http.StatusNotFound, nil), nil
	}

	delete(s.rules, firewallRuleId)

	return Response(http.StatusNoContent, nil), nil
}

// ClusterManagementV2ResourcesNetworkFirewallRulesV2FirewallRuleIdGet - Get cluster network firewall rule details
func (s *ClusterNetworkFirewallRuleV2APIService) ClusterManagementV2ResourcesNetworkFirewallRulesV2FirewallRuleIdGet(ctx context.Context, firewallRuleId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesNetworkFirewallRulesV2FirewallRuleIdGet with the required logic for this service method.
	// Add api_cluster_network_firewall_rule_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ClusterNetworkFirewallRuleV2{}) or use other options such as http.Ok ...
	// return Response(200, ClusterNetworkFirewallRuleV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ErrorListResponseV2{}) or use other options such as http.Ok ...
	// return Response(404, ErrorListResponseV2{}), nil

	s.mu.Lock()
	defer s.mu.Unlock()

	rule, exists := s.rules[firewallRuleId]
	if !exists {
		return Response(http.StatusNotFound, nil), nil
	}

	return Response(http.StatusOK, rule), nil
}

// ClusterManagementV2ResourcesNetworkFirewallRulesV2Post - Add a cluster network firewall rule
func (s *ClusterNetworkFirewallRuleV2APIService) ClusterManagementV2ResourcesNetworkFirewallRulesV2Post(ctx context.Context, clusterNetworkFirewallRuleV2 ClusterNetworkFirewallRuleV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesNetworkFirewallRulesV2Post with the required logic for this service method.
	// Add api_cluster_network_firewall_rule_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(202, ClusterNetworkFirewallRuleV2{}) or use other options such as http.Ok ...
	// return Response(202, ClusterNetworkFirewallRuleV2{}), nil

	// TODO: Uncomment the next line to return response Response(409, ErrorResponseV2{}) or use other options such as http.Ok ...
	// return Response(409, ErrorResponseV2{}), nil

	s.mu.Lock()
	defer s.mu.Unlock()

	id, err := uuid.NewUUID()
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}

	clusterNetworkFirewallRuleV2.Id = id.String()

	s.rules[clusterNetworkFirewallRuleV2.Id] = &clusterNetworkFirewallRuleV2

	return Response(http.StatusAccepted, &clusterNetworkFirewallRuleV2), nil
}
