/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
)

// BundleUserApiService is a service that implements the logic for the BundleUserApiServicer
// This service should implement the business logic for every endpoint for the BundleUserApi API.
// Include any external packages or services that will be required by this service.
type BundleUserApiService struct {
}

// NewBundleUserApiService creates a default api service
func NewBundleUserApiService() BundleUserApiServicer {
	return &BundleUserApiService{}
}

// CreateUser - Add a bundle user
func (s *BundleUserApiService) CreateUser(ctx context.Context, clusterId interface{}, bundle interface{}) (ImplResponse, error) {
	// TODO - update CreateUser with the required logic for this service method.
	// Add api_bundle_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	return Response(201, nil), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	//return Response(http.StatusNotImplemented, nil), errors.New("CreateUser method not implemented")
}

// DeleteUser - Delete a bundle user
func (s *BundleUserApiService) DeleteUser(ctx context.Context, clusterId interface{}, bundle interface{}) (ImplResponse, error) {
	// TODO - update DeleteUser with the required logic for this service method.
	// Add api_bundle_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	return Response(200, nil), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	//return Response(http.StatusNotImplemented, nil), errors.New("DeleteUser method not implemented")
}
