/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// CadenceClusterV2ApiController binds http requests to an api service and writes the service results to the http response
type CadenceClusterV2ApiController struct {
	service      CadenceClusterV2ApiServicer
	errorHandler ErrorHandler
}

// CadenceClusterV2ApiOption for how the controller is set up.
type CadenceClusterV2ApiOption func(*CadenceClusterV2ApiController)

// WithCadenceClusterV2ApiErrorHandler inject ErrorHandler into controller
func WithCadenceClusterV2ApiErrorHandler(h ErrorHandler) CadenceClusterV2ApiOption {
	return func(c *CadenceClusterV2ApiController) {
		c.errorHandler = h
	}
}

// NewCadenceClusterV2ApiController creates a default api controller
func NewCadenceClusterV2ApiController(s CadenceClusterV2ApiServicer, opts ...CadenceClusterV2ApiOption) Router {
	controller := &CadenceClusterV2ApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the CadenceClusterV2ApiController
func (c *CadenceClusterV2ApiController) Routes() Routes {
	return Routes{
		{
			"ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdDelete",
			strings.ToUpper("Delete"),
			"/cluster-management/v2/resources/applications/cadence/clusters/v2/{clusterId}",
			c.ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdDelete,
		},
		{
			"ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdGet",
			strings.ToUpper("Get"),
			"/cluster-management/v2/resources/applications/cadence/clusters/v2/{clusterId}",
			c.ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdGet,
		},
		{
			"ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdPut",
			strings.ToUpper("Put"),
			"/cluster-management/v2/resources/applications/cadence/clusters/v2/{clusterId}",
			c.ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdPut,
		},
		{
			"ClusterManagementV2ResourcesApplicationsCadenceClustersV2Post",
			strings.ToUpper("Post"),
			"/cluster-management/v2/resources/applications/cadence/clusters/v2/",
			c.ClusterManagementV2ResourcesApplicationsCadenceClustersV2Post,
		},
	}
}

// ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdDelete - Delete cluster
func (c *CadenceClusterV2ApiController) ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdDelete(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	clusterIdParam := params["clusterId"]

	result, err := c.service.ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdDelete(r.Context(), clusterIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdGet - Get Cadence cluster details.
func (c *CadenceClusterV2ApiController) ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	clusterIdParam := params["clusterId"]

	result, err := c.service.ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdGet(r.Context(), clusterIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdPut - Update a Cadence cluster
func (c *CadenceClusterV2ApiController) ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdPut(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	clusterIdParam := params["clusterId"]

	bodyParam := CadenceClusterUpdateV2{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bodyParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertCadenceClusterUpdateV2Required(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ClusterManagementV2ResourcesApplicationsCadenceClustersV2ClusterIdPut(r.Context(), clusterIdParam, bodyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ClusterManagementV2ResourcesApplicationsCadenceClustersV2Post - Create a Cadence cluster
func (c *CadenceClusterV2ApiController) ClusterManagementV2ResourcesApplicationsCadenceClustersV2Post(w http.ResponseWriter, r *http.Request) {
	bodyParam := CadenceClusterV2{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bodyParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertCadenceClusterV2Required(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ClusterManagementV2ResourcesApplicationsCadenceClustersV2Post(r.Context(), bodyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
