/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// PostgresqlClusterV2ApiService is a service that implements the logic for the PostgresqlClusterV2ApiServicer
// This service should implement the business logic for every endpoint for the PostgresqlClusterV2Api API.
// Include any external packages or services that will be required by this service.
type PostgresqlClusterV2ApiService struct {
}

// NewPostgresqlClusterV2ApiService creates a default api service
func NewPostgresqlClusterV2ApiService() PostgresqlClusterV2ApiServicer {
	return &PostgresqlClusterV2ApiService{}
}

// ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdDelete - Delete cluster
func (s *PostgresqlClusterV2ApiService) ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdDelete(ctx context.Context, clusterId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdDelete with the required logic for this service method.
	// Add api_postgresql_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdDelete method not implemented")
}

// ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdGet - Get Postgresql cluster details.
func (s *PostgresqlClusterV2ApiService) ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdGet(ctx context.Context, clusterId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdGet with the required logic for this service method.
	// Add api_postgresql_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, PostgresqlClusterV2{}) or use other options such as http.Ok ...
	//return Response(200, PostgresqlClusterV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdGet method not implemented")
}

// ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdPut - Update PostgreSQL cluster details
func (s *PostgresqlClusterV2ApiService) ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdPut(ctx context.Context, clusterId string, body PostgresqlClusterUpdateV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdPut with the required logic for this service method.
	// Add api_postgresql_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(202, PostgresqlClusterV2{}) or use other options such as http.Ok ...
	//return Response(202, PostgresqlClusterV2{}), nil

	//TODO: Uncomment the next line to return response Response(404, ErrorListResponseV2{}) or use other options such as http.Ok ...
	//return Response(404, ErrorListResponseV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2ClusterIdPut method not implemented")
}

// ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2Post - Create a Postgresql cluster.
func (s *PostgresqlClusterV2ApiService) ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2Post(ctx context.Context, body PostgresqlClusterV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2Post with the required logic for this service method.
	// Add api_postgresql_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(202, PostgresqlClusterV2{}) or use other options such as http.Ok ...
	//return Response(202, PostgresqlClusterV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesApplicationsPostgresqlClustersV2Post method not implemented")
}
