/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
)

// CassandraClusterV2ApiService is a service that implements the logic for the CassandraClusterV2ApiServicer
// This service should implement the business logic for every endpoint for the CassandraClusterV2Api API.
// Include any external packages or services that will be required by this service.
type CassandraClusterV2ApiService struct {
	MockCassandraCluster *CassandraClusterV2
}

// NewCassandraClusterV2ApiService creates a default api service
func NewCassandraClusterV2ApiService() CassandraClusterV2ApiServicer {
	return &CassandraClusterV2ApiService{}
}

// ClusterManagementV2ResourcesApplicationsCassandraClustersV2ClusterIdDelete - Delete cluster
func (s *CassandraClusterV2ApiService) ClusterManagementV2ResourcesApplicationsCassandraClustersV2ClusterIdDelete(ctx context.Context, clusterId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsCassandraClustersV2ClusterIdDelete with the required logic for this service method.
	// Add api_cassandra_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	s.MockCassandraCluster = nil
	return Response(204, nil), nil
}

// ClusterManagementV2ResourcesApplicationsCassandraClustersV2ClusterIdGet - Get Cassandra cluster details.
func (s *CassandraClusterV2ApiService) ClusterManagementV2ResourcesApplicationsCassandraClustersV2ClusterIdGet(ctx context.Context, clusterId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsCassandraClustersV2ClusterIdGet with the required logic for this service method.
	// Add api_cassandra_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	if s.MockCassandraCluster != nil {
		s.MockCassandraCluster.Status = RUNNING
	} else {
		return Response(404, nil), nil
	}

	return Response(200, s.MockCassandraCluster), nil
}

// ClusterManagementV2ResourcesApplicationsCassandraClustersV2ClusterIdPut - Update Cassandra Cluster Details
func (s *CassandraClusterV2ApiService) ClusterManagementV2ResourcesApplicationsCassandraClustersV2ClusterIdPut(ctx context.Context, clusterId string, body CassandraClusterUpdateV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsCassandraClustersV2ClusterIdPut with the required logic for this service method.
	// Add api_cassandra_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	newNode := []NodeDetailsV2{{
		Rack:          "us-east-1a",
		NodeSize:      body.DataCentres[0].NodeSize,
		PublicAddress: "54.146.160.89",
	}}

	s.MockCassandraCluster.DataCentres[0].Nodes = newNode

	return Response(202, nil), nil
	//TODO: Uncomment the next line to return response Response(404, ErrorListResponseV2{}) or use other options such as http.Ok ...
	//return Response(404, ErrorListResponseV2{}), nil
}

// ClusterManagementV2ResourcesApplicationsCassandraClustersV2Post - Create a Cassandra cluster.
func (s *CassandraClusterV2ApiService) ClusterManagementV2ResourcesApplicationsCassandraClustersV2Post(ctx context.Context, body CassandraClusterV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesApplicationsCassandraClustersV2Post with the required logic for this service method.
	// Add api_cassandra_cluster_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	s.MockCassandraCluster = &body
	s.MockCassandraCluster.Id = CreatedID
	s.MockCassandraCluster.DataCentres[0].Nodes = []NodeDetailsV2{{NodeSize: body.DataCentres[0].NodeSize}}
	return Response(202, s.MockCassandraCluster), nil
}
