/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// KafkaClusterV2ApiController binds http requests to an api service and writes the service results to the http response
type KafkaClusterV2ApiController struct {
	service      KafkaClusterV2ApiServicer
	errorHandler ErrorHandler
}

// KafkaClusterV2ApiOption for how the controller is set up.
type KafkaClusterV2ApiOption func(*KafkaClusterV2ApiController)

// WithKafkaClusterV2ApiErrorHandler inject ErrorHandler into controller
func WithKafkaClusterV2ApiErrorHandler(h ErrorHandler) KafkaClusterV2ApiOption {
	return func(c *KafkaClusterV2ApiController) {
		c.errorHandler = h
	}
}

// NewKafkaClusterV2ApiController creates a default api controller
func NewKafkaClusterV2ApiController(s KafkaClusterV2ApiServicer, opts ...KafkaClusterV2ApiOption) Router {
	controller := &KafkaClusterV2ApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the KafkaClusterV2ApiController
func (c *KafkaClusterV2ApiController) Routes() Routes {
	return Routes{
		{
			"ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdDelete",
			strings.ToUpper("Delete"),
			"/cluster-management/v2/resources/applications/kafka/clusters/v2/{clusterId}",
			c.ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdDelete,
		},
		{
			"ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdGet",
			strings.ToUpper("Get"),
			"/cluster-management/v2/resources/applications/kafka/clusters/v2/{clusterId}",
			c.ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdGet,
		},
		{
			"ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdPut",
			strings.ToUpper("Put"),
			"/cluster-management/v2/resources/applications/kafka/clusters/v2/{clusterId}",
			c.ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdPut,
		},
		{
			"ClusterManagementV2ResourcesApplicationsKafkaClustersV2Post",
			strings.ToUpper("Post"),
			"/cluster-management/v2/resources/applications/kafka/clusters/v2",
			c.ClusterManagementV2ResourcesApplicationsKafkaClustersV2Post,
		},
	}
}

// ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdDelete - Delete cluster
func (c *KafkaClusterV2ApiController) ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdDelete(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	clusterIdParam := params["clusterId"]

	result, err := c.service.ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdDelete(r.Context(), clusterIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdGet - Get Kafka cluster details.
func (c *KafkaClusterV2ApiController) ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	clusterIdParam := params["clusterId"]

	result, err := c.service.ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdGet(r.Context(), clusterIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdPut - Update Kafka Cluster Details
func (c *KafkaClusterV2ApiController) ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdPut(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	clusterIdParam := params["clusterId"]

	bodyParam := KafkaClusterUpdateV2{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bodyParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertKafkaClusterUpdateV2Required(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ClusterManagementV2ResourcesApplicationsKafkaClustersV2ClusterIdPut(r.Context(), clusterIdParam, bodyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ClusterManagementV2ResourcesApplicationsKafkaClustersV2Post - Create a Kafka cluster.
func (c *KafkaClusterV2ApiController) ClusterManagementV2ResourcesApplicationsKafkaClustersV2Post(w http.ResponseWriter, r *http.Request) {
	bodyParam := KafkaClusterV2{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bodyParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertKafkaClusterV2Required(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ClusterManagementV2ResourcesApplicationsKafkaClustersV2Post(r.Context(), bodyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
