/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// GCPVPCPeerV2APIService is a service that implements the logic for the GCPVPCPeerV2APIServicer
// This service should implement the business logic for every endpoint for the GCPVPCPeerV2API API.
// Include any external packages or services that will be required by this service.
type GCPVPCPeerV2APIService struct {
}

// NewGCPVPCPeerV2APIService creates a default api service
func NewGCPVPCPeerV2APIService() GCPVPCPeerV2APIServicer {
	return &GCPVPCPeerV2APIService{}
}

// ClusterManagementV2DataSourcesProvidersGcpVpcPeersV2Get - List all GCP VPC Peering requests
func (s *GCPVPCPeerV2APIService) ClusterManagementV2DataSourcesProvidersGcpVpcPeersV2Get(ctx context.Context) (ImplResponse, error) {
	// TODO - update ClusterManagementV2DataSourcesProvidersGcpVpcPeersV2Get with the required logic for this service method.
	// Add api_gcpvpc_peer_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []AccountGcpVpcPeersV2{}) or use other options such as http.Ok ...
	// return Response(200, []AccountGcpVpcPeersV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2DataSourcesProvidersGcpVpcPeersV2Get method not implemented")
}

// ClusterManagementV2ResourcesProvidersGcpVpcPeersV2Post - Create GCP VPC Peering Request
func (s *GCPVPCPeerV2APIService) ClusterManagementV2ResourcesProvidersGcpVpcPeersV2Post(ctx context.Context, gcpVpcPeerV2 GcpVpcPeerV2) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesProvidersGcpVpcPeersV2Post with the required logic for this service method.
	// Add api_gcpvpc_peer_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(202, GcpVpcPeerV2{}) or use other options such as http.Ok ...
	// return Response(202, GcpVpcPeerV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesProvidersGcpVpcPeersV2Post method not implemented")
}

// ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdDelete - Delete GCP VPC Peering Connection
func (s *GCPVPCPeerV2APIService) ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdDelete(ctx context.Context, vpcPeerId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdDelete with the required logic for this service method.
	// Add api_gcpvpc_peer_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, ErrorListResponseV2{}) or use other options such as http.Ok ...
	// return Response(404, ErrorListResponseV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdDelete method not implemented")
}

// ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdGet - Get GCP VPC Peering Connection info
func (s *GCPVPCPeerV2APIService) ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdGet(ctx context.Context, vpcPeerId string) (ImplResponse, error) {
	// TODO - update ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdGet with the required logic for this service method.
	// Add api_gcpvpc_peer_v2_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GcpVpcPeerV2{}) or use other options such as http.Ok ...
	// return Response(200, GcpVpcPeerV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ErrorListResponseV2{}) or use other options such as http.Ok ...
	// return Response(404, ErrorListResponseV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ClusterManagementV2ResourcesProvidersGcpVpcPeersV2VpcPeerIdGet method not implemented")
}
