/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaRestProxyUserPasswordV2 - Definition of a Kafka Rest Proxy User Password Update to be applied to a Kafka Rest Proxy user.
type KafkaRestProxyUserPasswordV2 struct {

	// Password for the Kafka Rest Proxy user.
	Password string `json:"password"`
}

// AssertKafkaRestProxyUserPasswordV2Required checks if the required fields are not zero-ed
func AssertKafkaRestProxyUserPasswordV2Required(obj KafkaRestProxyUserPasswordV2) error {
	elements := map[string]interface{}{
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKafkaRestProxyUserPasswordV2Constraints checks if the values respects the defined constraints
func AssertKafkaRestProxyUserPasswordV2Constraints(obj KafkaRestProxyUserPasswordV2) error {
	return nil
}
