/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaUserUpdateV3 - Definition of a Kafka User Update to be applied to a Kafka cluster.
type KafkaUserUpdateV3 struct {

	// Password for the Kafka user.
	Password string `json:"password,omitempty"`

	// Overwrite user if already exists.
	OverrideExistingUser bool `json:"overrideExistingUser,omitempty"`

	SaslScramMechanism KafkaSaslScramMechanismEnum `json:"saslScramMechanism,omitempty"`

	AuthMechanism KafkaAuthMechanismsEnumV2 `json:"authMechanism"`

	// ID of the Kafka cluster.
	ClusterId string `json:"clusterId"`

	// Instaclustr identifier for the Kafka user. The value of this property has the form: [cluster-id]_[kafka-username]
	Id string `json:"id,omitempty"`

	// Username of the Kafka user.
	Username string `json:"username"`
}

// AssertKafkaUserUpdateV3Required checks if the required fields are not zero-ed
func AssertKafkaUserUpdateV3Required(obj KafkaUserUpdateV3) error {
	elements := map[string]interface{}{
		"authMechanism": obj.AuthMechanism,
		"clusterId":     obj.ClusterId,
		"username":      obj.Username,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKafkaUserUpdateV3Constraints checks if the values respects the defined constraints
func AssertKafkaUserUpdateV3Constraints(obj KafkaUserUpdateV3) error {
	return nil
}
