/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AddonBundles struct {

	// Bundle
	Bundle string `json:"bundle,omitempty"`

	// Version
	Version string `json:"version,omitempty"`

	Options AddonBundlesOptions `json:"options,omitempty"`
}

// AssertAddonBundlesRequired checks if the required fields are not zero-ed
func AssertAddonBundlesRequired(obj AddonBundles) error {
	if err := AssertAddonBundlesOptionsRequired(obj.Options); err != nil {
		return err
	}
	return nil
}

// AssertAddonBundlesConstraints checks if the values respects the defined constraints
func AssertAddonBundlesConstraints(obj AddonBundles) error {
	return nil
}
