/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaTopicConfigV2 - Definition of a Kafka Topic Config to be applied to a Kafka topic of a cluster
type KafkaTopicConfigV2 struct {

	// Kafka Topic config value
	Value string `json:"value"`

	// Kafka Topic config key
	Key string `json:"key"`
}

// AssertKafkaTopicConfigV2Required checks if the required fields are not zero-ed
func AssertKafkaTopicConfigV2Required(obj KafkaTopicConfigV2) error {
	elements := map[string]interface{}{
		"value": obj.Value,
		"key":   obj.Key,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseKafkaTopicConfigV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of KafkaTopicConfigV2 (e.g. [][]KafkaTopicConfigV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseKafkaTopicConfigV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aKafkaTopicConfigV2, ok := obj.(KafkaTopicConfigV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertKafkaTopicConfigV2Required(aKafkaTopicConfigV2)
	})
}
