/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ErrorListResponseV2 struct {
	Errors []ErrorResponseV2 `json:"errors,omitempty"`
}

// AssertErrorListResponseV2Required checks if the required fields are not zero-ed
func AssertErrorListResponseV2Required(obj ErrorListResponseV2) error {
	for _, el := range obj.Errors {
		if err := AssertErrorResponseV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertErrorListResponseV2Constraints checks if the values respects the defined constraints
func AssertErrorListResponseV2Constraints(obj ErrorListResponseV2) error {
	return nil
}
