/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaTopicConfigsV2 - A listable data source of all topic configs within a Kafka topic
type KafkaTopicConfigsV2 struct {

	// list of Kafka topic configs
	Configs []KafkaTopicConfigV2 `json:"configs"`
}

// AssertKafkaTopicConfigsV2Required checks if the required fields are not zero-ed
func AssertKafkaTopicConfigsV2Required(obj KafkaTopicConfigsV2) error {
	elements := map[string]interface{}{
		"configs": obj.Configs,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Configs {
		if err := AssertKafkaTopicConfigV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertKafkaTopicConfigsV2Constraints checks if the values respects the defined constraints
func AssertKafkaTopicConfigsV2Constraints(obj KafkaTopicConfigsV2) error {
	return nil
}
