/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// RedisUserSummariesV2 - A listable data source of all Redis users within a Redis Cluster.
type RedisUserSummariesV2 struct {

	// List of all Redis users in the cluster.
	RedisUsers []RedisUserSummaryV2 `json:"redisUsers,omitempty"`

	// ID of the redis cluster
	ClusterId string `json:"clusterId,omitempty"`
}

// AssertRedisUserSummariesV2Required checks if the required fields are not zero-ed
func AssertRedisUserSummariesV2Required(obj RedisUserSummariesV2) error {
	for _, el := range obj.RedisUsers {
		if err := AssertRedisUserSummaryV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRedisUserSummariesV2Constraints checks if the values respects the defined constraints
func AssertRedisUserSummariesV2Constraints(obj RedisUserSummariesV2) error {
	return nil
}
