/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UpdateMaintenanceEventScheduleRequest struct {

	// The time this maintenance event should be rescheduled to start at (in UTC time)
	ScheduledStartTime string `json:"scheduledStartTime,omitempty"`

	ValidationMessages map[string]string `json:"validationMessages,omitempty"`
}

// AssertUpdateMaintenanceEventScheduleRequestRequired checks if the required fields are not zero-ed
func AssertUpdateMaintenanceEventScheduleRequestRequired(obj UpdateMaintenanceEventScheduleRequest) error {
	return nil
}

// AssertUpdateMaintenanceEventScheduleRequestConstraints checks if the values respects the defined constraints
func AssertUpdateMaintenanceEventScheduleRequestConstraints(obj UpdateMaintenanceEventScheduleRequest) error {
	return nil
}
