/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaConnectExternalSourceClusterDetailsV2 -
type KafkaConnectExternalSourceClusterDetailsV2 struct {

	// Kafka connection properties string used to connect to external kafka cluster
	SourceConnectionProperties string `json:"sourceConnectionProperties"`
}

// AssertKafkaConnectExternalSourceClusterDetailsV2Required checks if the required fields are not zero-ed
func AssertKafkaConnectExternalSourceClusterDetailsV2Required(obj KafkaConnectExternalSourceClusterDetailsV2) error {
	elements := map[string]interface{}{
		"sourceConnectionProperties": obj.SourceConnectionProperties,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseKafkaConnectExternalSourceClusterDetailsV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of KafkaConnectExternalSourceClusterDetailsV2 (e.g. [][]KafkaConnectExternalSourceClusterDetailsV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseKafkaConnectExternalSourceClusterDetailsV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aKafkaConnectExternalSourceClusterDetailsV2, ok := obj.(KafkaConnectExternalSourceClusterDetailsV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertKafkaConnectExternalSourceClusterDetailsV2Required(aKafkaConnectExternalSourceClusterDetailsV2)
	})
}
