/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// FirewallRuleTypesV2 : The type of firewall rule.
type FirewallRuleTypesV2 string

// List of FirewallRuleTypesV2
//const (
//	APACHE_ZOOKEEPER         FirewallRuleTypesV2 = "APACHE_ZOOKEEPER"
//	CADENCE                  FirewallRuleTypesV2 = "CADENCE"
//	CADENCE_GRPC             FirewallRuleTypesV2 = "CADENCE_GRPC"
//	CADENCE_WEB              FirewallRuleTypesV2 = "CADENCE_WEB"
//	CASSANDRA                FirewallRuleTypesV2 = "CASSANDRA"
//	CASSANDRA_CQL            FirewallRuleTypesV2 = "CASSANDRA_CQL"
//	ELASTICSEARCH            FirewallRuleTypesV2 = "ELASTICSEARCH"
//	KAFKA                    FirewallRuleTypesV2 = "KAFKA"
//	KAFKA_CONNECT            FirewallRuleTypesV2 = "KAFKA_CONNECT"
//	KAFKA_ENCRYPTION         FirewallRuleTypesV2 = "KAFKA_ENCRYPTION"
//	KAFKA_MTLS               FirewallRuleTypesV2 = "KAFKA_MTLS"
//	KAFKA_NO_ENCRYPTION      FirewallRuleTypesV2 = "KAFKA_NO_ENCRYPTION"
//	KAFKA_REST_PROXY         FirewallRuleTypesV2 = "KAFKA_REST_PROXY"
//	KAFKA_SCHEMA_REGISTRY    FirewallRuleTypesV2 = "KAFKA_SCHEMA_REGISTRY"
//	KARAPACE_REST_PROXY      FirewallRuleTypesV2 = "KARAPACE_REST_PROXY"
//	KARAPACE_SCHEMA_REGISTRY FirewallRuleTypesV2 = "KARAPACE_SCHEMA_REGISTRY"
//	MONGODB                  FirewallRuleTypesV2 = "MONGODB"
//	OPENSEARCH               FirewallRuleTypesV2 = "OPENSEARCH"
//	OPENSEARCH_DASHBOARDS    FirewallRuleTypesV2 = "OPENSEARCH_DASHBOARDS"
//	PGBOUNCER                FirewallRuleTypesV2 = "PGBOUNCER"
//	POSTGRESQL               FirewallRuleTypesV2 = "POSTGRESQL"
//	REDIS                    FirewallRuleTypesV2 = "REDIS"
//	SEARCH_DASHBOARDS        FirewallRuleTypesV2 = "SEARCH_DASHBOARDS"
//	SECURE_APACHE_ZOOKEEPER  FirewallRuleTypesV2 = "SECURE_APACHE_ZOOKEEPER"
//	SPARK                    FirewallRuleTypesV2 = "SPARK"
//	SPARK_JOBSERVER          FirewallRuleTypesV2 = "SPARK_JOBSERVER"
//	SHOTOVER_PROXY           FirewallRuleTypesV2 = "SHOTOVER_PROXY"
//)

// AssertFirewallRuleTypesV2Required checks if the required fields are not zero-ed
func AssertFirewallRuleTypesV2Required(obj FirewallRuleTypesV2) error {
	return nil
}

// AssertRecurseFirewallRuleTypesV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FirewallRuleTypesV2 (e.g. [][]FirewallRuleTypesV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFirewallRuleTypesV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFirewallRuleTypesV2, ok := obj.(FirewallRuleTypesV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFirewallRuleTypesV2Required(aFirewallRuleTypesV2)
	})
}
