/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccountAzureVnetPeersV2 - A listable data source of all Azure Virtual Network Peering requests in an Instaclustr Account.
type AccountAzureVnetPeersV2 struct {

	// UUID of the Instaclustr Account.
	AccountId string `json:"accountId,omitempty"`

	//
	PeeringRequests []AzureVnetPeerSummaryV2 `json:"peeringRequests,omitempty"`
}

// AssertAccountAzureVnetPeersV2Required checks if the required fields are not zero-ed
func AssertAccountAzureVnetPeersV2Required(obj AccountAzureVnetPeersV2) error {
	for _, el := range obj.PeeringRequests {
		if err := AssertAzureVnetPeerSummaryV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseAccountAzureVnetPeersV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AccountAzureVnetPeersV2 (e.g. [][]AccountAzureVnetPeersV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAccountAzureVnetPeersV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAccountAzureVnetPeersV2, ok := obj.(AccountAzureVnetPeersV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAccountAzureVnetPeersV2Required(aAccountAzureVnetPeersV2)
	})
}
