/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AwsVpcPeerUpdateV2 struct {

	// The subnets for the peering VPC.
	PeerSubnets []string `json:"peerSubnets"`
}

// AssertAwsVpcPeerUpdateV2Required checks if the required fields are not zero-ed
func AssertAwsVpcPeerUpdateV2Required(obj AwsVpcPeerUpdateV2) error {
	elements := map[string]interface{}{
		"peerSubnets": obj.PeerSubnets,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseAwsVpcPeerUpdateV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AwsVpcPeerUpdateV2 (e.g. [][]AwsVpcPeerUpdateV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAwsVpcPeerUpdateV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAwsVpcPeerUpdateV2, ok := obj.(AwsVpcPeerUpdateV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAwsVpcPeerUpdateV2Required(aAwsVpcPeerUpdateV2)
	})
}
