/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaRestProxyUserSummariesV2 - A listable data source of all Kafka Rest Proxy users within a Kafka Cluster.
type KafkaRestProxyUserSummariesV2 struct {

	// ID of the kafka cluster
	ClusterId string `json:"clusterId,omitempty"`

	// List of all Kafka Rest Proxy users in the cluster.
	KafkaRestProxyUsers []KafkaRestProxyUserSummaryV2 `json:"kafkaRestProxyUsers,omitempty"`
}

// AssertKafkaRestProxyUserSummariesV2Required checks if the required fields are not zero-ed
func AssertKafkaRestProxyUserSummariesV2Required(obj KafkaRestProxyUserSummariesV2) error {
	for _, el := range obj.KafkaRestProxyUsers {
		if err := AssertKafkaRestProxyUserSummaryV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertKafkaRestProxyUserSummariesV2Constraints checks if the values respects the defined constraints
func AssertKafkaRestProxyUserSummariesV2Constraints(obj KafkaRestProxyUserSummariesV2) error {
	return nil
}
