/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PgbouncerPoolSchema struct {
	Database string `json:"database,omitempty"`

	Users []string `json:"users,omitempty"`
}

// AssertPgbouncerPoolSchemaRequired checks if the required fields are not zero-ed
func AssertPgbouncerPoolSchemaRequired(obj PgbouncerPoolSchema) error {
	return nil
}

// AssertPgbouncerPoolSchemaConstraints checks if the values respects the defined constraints
func AssertPgbouncerPoolSchemaConstraints(obj PgbouncerPoolSchema) error {
	return nil
}
