/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type KafkaAclDeleteRequest struct {

	// Valid values must start with \"User:\" including the wildcard, e.g., \"User:*\"
	Principal string `json:"principal,omitempty"`

	// It takes any string including the wildcard \"*\"
	Host string `json:"host,omitempty"`

	// Valid values for resourceType: \"CLUSTER\", \"TOPIC\", \"GROUP\", \"DELEGATION_TOKEN\", \"TRANSACTIONAL_ID\", \"ANY\"
	ResourceType string `json:"resourceType,omitempty"`

	// It takes any string including the wildcard \"*\"
	ResourceName string `json:"resourceName,omitempty"`

	// Valid values for operation: \"ANY\", \"ALL\", \"READ\", \"WRITE\", \"CREATE\", \"DELETE\", \"ALTER\", \"DESCRIBE\", \"CLUSTER_ACTION\", \"DESCRIBE_CONFIGS\", \"ALTER_CONFIGS\", \"IDEMPOTENT_WRITE\"
	Operation string `json:"operation,omitempty"`

	// Valid values for permissionType: \"ALLOW\", \"DENY\", \"ANY\"
	PermissionType string `json:"permissionType,omitempty"`

	// Valid values for patternType: \"LITERAL\", \"PREFIXED\", \"MATCH\", \"ANY\"
	PatternType string `json:"patternType,omitempty"`

	ValidationMessages map[string]string `json:"validationMessages,omitempty"`
}

// AssertKafkaAclDeleteRequestRequired checks if the required fields are not zero-ed
func AssertKafkaAclDeleteRequestRequired(obj KafkaAclDeleteRequest) error {
	return nil
}

// AssertKafkaAclDeleteRequestConstraints checks if the values respects the defined constraints
func AssertKafkaAclDeleteRequestConstraints(obj KafkaAclDeleteRequest) error {
	return nil
}
