/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KarapaceSchemaRegistryUserPasswordV2 - Definition of a Karapace Schema Registry User Password Update to be applied to a Karapace Schema Registry user.
type KarapaceSchemaRegistryUserPasswordV2 struct {

	// Password for the Karapace Schema Registry user.
	Password string `json:"password"`
}

// AssertKarapaceSchemaRegistryUserPasswordV2Required checks if the required fields are not zero-ed
func AssertKarapaceSchemaRegistryUserPasswordV2Required(obj KarapaceSchemaRegistryUserPasswordV2) error {
	elements := map[string]interface{}{
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKarapaceSchemaRegistryUserPasswordV2Constraints checks if the values respects the defined constraints
func AssertKarapaceSchemaRegistryUserPasswordV2Constraints(obj KarapaceSchemaRegistryUserPasswordV2) error {
	return nil
}
