/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CassandraOptionsSchema struct {

	// Accepts true/false. Enables Password Authentication and User Authorization.
	AuthnAuthz bool `json:"authnAuthz,omitempty"`

	// Accepts true/false. Enables Client ⇄ Node Encryption.
	ClientEncryption bool `json:"clientEncryption,omitempty"`

	// Enables broadcast of private IPs for auto-discovery.
	UsePrivateBroadcastRPCAddress bool `json:"usePrivateBroadcastRPCAddress,omitempty"`

	// Enables broadcast of private IPs for auto-discovery.
	LuceneEnabled bool `json:"luceneEnabled,omitempty"`

	// Enables commitlog backups and increases the frequency of the default snapshot backups. This option replaces options.backupEnabled.
	ContinuousBackupEnabled bool `json:"continuousBackupEnabled,omitempty"`
}

// AssertCassandraOptionsSchemaRequired checks if the required fields are not zero-ed
func AssertCassandraOptionsSchemaRequired(obj CassandraOptionsSchema) error {
	return nil
}

// AssertCassandraOptionsSchemaConstraints checks if the values respects the defined constraints
func AssertCassandraOptionsSchemaConstraints(obj CassandraOptionsSchema) error {
	return nil
}
