/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KarapaceRestProxyUserSummariesV2 - A listable data source of all Karapace Rest Proxy users within a Kafka Cluster.
type KarapaceRestProxyUserSummariesV2 struct {

	// List of all Karapace Rest Proxy users in the cluster.
	KarapaceRestProxyUsers []KarapaceRestProxyUserSummaryV2 `json:"karapaceRestProxyUsers,omitempty"`

	// ID of the kafka cluster
	ClusterId string `json:"clusterId,omitempty"`
}

// AssertKarapaceRestProxyUserSummariesV2Required checks if the required fields are not zero-ed
func AssertKarapaceRestProxyUserSummariesV2Required(obj KarapaceRestProxyUserSummariesV2) error {
	for _, el := range obj.KarapaceRestProxyUsers {
		if err := AssertKarapaceRestProxyUserSummaryV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertKarapaceRestProxyUserSummariesV2Constraints checks if the values respects the defined constraints
func AssertKarapaceRestProxyUserSummariesV2Constraints(obj KarapaceRestProxyUserSummariesV2) error {
	return nil
}
