/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaSchemaRegistryUserPasswordV2 - Definition of a Kafka Schema Registry User Password Update to be applied to a Kafka Schema Registry user.
type KafkaSchemaRegistryUserPasswordV2 struct {

	// Password for the Kafka Schema Registry user.
	Password string `json:"password"`
}

// AssertKafkaSchemaRegistryUserPasswordV2Required checks if the required fields are not zero-ed
func AssertKafkaSchemaRegistryUserPasswordV2Required(obj KafkaSchemaRegistryUserPasswordV2) error {
	elements := map[string]interface{}{
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKafkaSchemaRegistryUserPasswordV2Constraints checks if the values respects the defined constraints
func AssertKafkaSchemaRegistryUserPasswordV2Constraints(obj KafkaSchemaRegistryUserPasswordV2) error {
	return nil
}
