/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type KafkaConnectExternalTargetClusterDetailsV2 struct {

	// Connection information for your Kafka Cluster. These options are analogous to the similarly named options that you would place in your Kafka Connect worker.properties file. Only required if connecting to a Non-Instaclustr managed Kafka Cluster.
	SecurityProtocol string `json:"securityProtocol,omitempty"`

	// Connection information for your Kafka Cluster. These options are analogous to the similarly named options that you would place in your Kafka Connect worker.properties file. Only required if connecting to a Non-Instaclustr managed Kafka Cluster.
	SslTruststorePassword string `json:"sslTruststorePassword,omitempty"`

	// Connection information for your Kafka Cluster. These options are analogous to the similarly named options that you would place in your Kafka Connect worker.properties file. Only required if connecting to a Non-Instaclustr managed Kafka Cluster.
	BootstrapServers string `json:"bootstrapServers,omitempty"`

	// Connection information for your Kafka Cluster. These options are analogous to the similarly named options that you would place in your Kafka Connect worker.properties file. Only required if connecting to a Non-Instaclustr managed Kafka Cluster.
	SaslJaasConfig string `json:"saslJaasConfig,omitempty"`

	// Connection information for your Kafka Cluster. These options are analogous to the similarly named options that you would place in your Kafka Connect worker.properties file. Only required if connecting to a Non-Instaclustr managed Kafka Cluster.
	SaslMechanism string `json:"saslMechanism,omitempty"`

	// Connection information for your Kafka Cluster. These options are analogous to the similarly named options that you would place in your Kafka Connect worker.properties file. Only required if connecting to a Non-Instaclustr managed Kafka Cluster.
	SslProtocol string `json:"sslProtocol,omitempty"`

	// Connection information for your Kafka Cluster. These options are analogous to the similarly named options that you would place in your Kafka Connect worker.properties file. Only required if connecting to a Non-Instaclustr managed Kafka Cluster.
	SslEnabledProtocols string `json:"sslEnabledProtocols,omitempty"`

	// Base64 encoded version of the TLS trust store (in JKS format) used to connect to your Kafka Cluster. Only required if connecting to a Non-Instaclustr managed Kafka Cluster with TLS enabled.
	Truststore string `json:"truststore,omitempty"`
}

// AssertKafkaConnectExternalTargetClusterDetailsV2Required checks if the required fields are not zero-ed
func AssertKafkaConnectExternalTargetClusterDetailsV2Required(obj KafkaConnectExternalTargetClusterDetailsV2) error {
	return nil
}

// AssertKafkaConnectExternalTargetClusterDetailsV2Constraints checks if the values respects the defined constraints
func AssertKafkaConnectExternalTargetClusterDetailsV2Constraints(obj KafkaConnectExternalTargetClusterDetailsV2) error {
	return nil
}
