/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiRestoreRequest struct {
	PointInTime string `json:"pointInTime,omitempty"`

	ClusterNetwork string `json:"clusterNetwork,omitempty"`

	KeyspaceTables string `json:"keyspaceTables,omitempty"`

	IndexNames string `json:"indexNames,omitempty"`

	ClusterName string `json:"clusterName,omitempty"`

	CdcInfos []RestoreCdcInfo `json:"cdcInfos,omitempty"`

	ClusterNameOverride string `json:"clusterNameOverride,omitempty"`
}

// AssertApiRestoreRequestRequired checks if the required fields are not zero-ed
func AssertApiRestoreRequestRequired(obj ApiRestoreRequest) error {
	for _, el := range obj.CdcInfos {
		if err := AssertRestoreCdcInfoRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertApiRestoreRequestConstraints checks if the values respects the defined constraints
func AssertApiRestoreRequestConstraints(obj ApiRestoreRequest) error {
	return nil
}
