/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateClusterResponseSchema struct {
	Id string `json:"id,omitempty"`
}

// AssertCreateClusterResponseSchemaRequired checks if the required fields are not zero-ed
func AssertCreateClusterResponseSchemaRequired(obj CreateClusterResponseSchema) error {
	return nil
}

// AssertCreateClusterResponseSchemaConstraints checks if the values respects the defined constraints
func AssertCreateClusterResponseSchemaConstraints(obj CreateClusterResponseSchema) error {
	return nil
}
