/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PostgresqlConfigurationPropertyUpdateV2 - PostgreSQL configuration property. Cluster nodes will need to be manually [reloaded](https://www.instaclustr.com/support/documentation/postgresql/postgresql-operations/reloading-a-node/) to apply configuration changes.
type PostgresqlConfigurationPropertyUpdateV2 struct {

	// Value of the configuration property.
	Value string `json:"value"`
}

// AssertPostgresqlConfigurationPropertyUpdateV2Required checks if the required fields are not zero-ed
func AssertPostgresqlConfigurationPropertyUpdateV2Required(obj PostgresqlConfigurationPropertyUpdateV2) error {
	elements := map[string]interface{}{
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecursePostgresqlConfigurationPropertyUpdateV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PostgresqlConfigurationPropertyUpdateV2 (e.g. [][]PostgresqlConfigurationPropertyUpdateV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePostgresqlConfigurationPropertyUpdateV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPostgresqlConfigurationPropertyUpdateV2, ok := obj.(PostgresqlConfigurationPropertyUpdateV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPostgresqlConfigurationPropertyUpdateV2Required(aPostgresqlConfigurationPropertyUpdateV2)
	})
}
