/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AwsEndpointServicePrincipalsResponse struct {

	// List of IAM Principal ARNs of the Endpoint Service
	IamPrincipalARNs []string `json:"iamPrincipalARNs,omitempty"`
}

// AssertAwsEndpointServicePrincipalsResponseRequired checks if the required fields are not zero-ed
func AssertAwsEndpointServicePrincipalsResponseRequired(obj AwsEndpointServicePrincipalsResponse) error {
	return nil
}

// AssertAwsEndpointServicePrincipalsResponseConstraints checks if the values respects the defined constraints
func AssertAwsEndpointServicePrincipalsResponseConstraints(obj AwsEndpointServicePrincipalsResponse) error {
	return nil
}
