/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// VpcTypeV2 :
type VpcTypeV2 string

// List of VpcTypeV2
const (
	TARGET_VPC   VpcTypeV2 = "TARGET_VPC"
	VPC_PEERED   VpcTypeV2 = "VPC_PEERED"
	SEPARATE_VPC VpcTypeV2 = "SEPARATE_VPC"
)

// AssertVpcTypeV2Required checks if the required fields are not zero-ed
func AssertVpcTypeV2Required(obj VpcTypeV2) error {
	return nil
}

// AssertRecurseVpcTypeV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of VpcTypeV2 (e.g. [][]VpcTypeV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseVpcTypeV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aVpcTypeV2, ok := obj.(VpcTypeV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertVpcTypeV2Required(aVpcTypeV2)
	})
}
