/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AwsVpcPeeringConnection struct {

	// ID of the VPC peering connection
	Id string `json:"id,omitempty"`

	// ID of VPC peering connection on AWS
	AwsVpcConnectionId string `json:"aws_vpc_connection_id,omitempty"`

	// ID of the Cluster Data Centre
	ClusterDataCentre string `json:"clusterDataCentre,omitempty"`

	// AWS VPC ID for the Cluster Data Centre
	VpcId string `json:"vpcId,omitempty"`

	// ID of the VPC with which you are creating the peering connection
	PeerVpcId string `json:"peerVpcId,omitempty"`

	// The account ID of the owner of the accepter VPC
	PeerAccountId string `json:"peerAccountId,omitempty"`

	PeerSubnet CidrSchema `json:"peerSubnet,omitempty"`

	// Region code for the accepter VPC, if the accepter VPC is located in a region other than the region in which you make the request.
	PeerRegion string `json:"peerRegion,omitempty"`

	PeerSubnets AwsVpcPeeringConnectionPeerSubnets `json:"peerSubnets,omitempty"`
}

// AssertAwsVpcPeeringConnectionRequired checks if the required fields are not zero-ed
func AssertAwsVpcPeeringConnectionRequired(obj AwsVpcPeeringConnection) error {
	if err := AssertCidrSchemaRequired(obj.PeerSubnet); err != nil {
		return err
	}
	if err := AssertAwsVpcPeeringConnectionPeerSubnetsRequired(obj.PeerSubnets); err != nil {
		return err
	}
	return nil
}

// AssertAwsVpcPeeringConnectionConstraints checks if the values respects the defined constraints
func AssertAwsVpcPeeringConnectionConstraints(obj AwsVpcPeeringConnection) error {
	return nil
}
