/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OpenSearchDataNodeV2 struct {
	NodeSize string `json:"nodeSize"`

	// Number of nodes
	NodeCount int32 `json:"nodeCount"`

	// Indicates if the data nodes on the cluster is dedicated data node or not. All data nodes will be converted to dedicated data nodes if ingest nodes are added, and new data nodes will be added as dedicated data nodes if the cluster has ingest nodes.
	DedicatedDataNode bool `json:"dedicatedDataNode,omitempty"`
}

// AssertOpenSearchDataNodeV2Required checks if the required fields are not zero-ed
func AssertOpenSearchDataNodeV2Required(obj OpenSearchDataNodeV2) error {
	elements := map[string]interface{}{
		"nodeSize":  obj.NodeSize,
		"nodeCount": obj.NodeCount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertOpenSearchDataNodeV2Constraints checks if the values respects the defined constraints
func AssertOpenSearchDataNodeV2Constraints(obj OpenSearchDataNodeV2) error {
	return nil
}
