/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ErrorCollectionResponse struct {
	Errors map[string]string `json:"errors,omitempty"`
}

// AssertErrorCollectionResponseRequired checks if the required fields are not zero-ed
func AssertErrorCollectionResponseRequired(obj ErrorCollectionResponse) error {
	return nil
}

// AssertErrorCollectionResponseConstraints checks if the values respects the defined constraints
func AssertErrorCollectionResponseConstraints(obj ErrorCollectionResponse) error {
	return nil
}
