/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"os"
)

type KafkaConnectOptionsSchema struct {

	// GUID of the Instaclustr managed Kafka Cluster Id you wish to connect to. Must be in the same Instaclustr account.
	TargetKafkaClusterId string `json:"targetKafkaClusterId,omitempty"`

	// Only required if targeting an Instaclustr managed cluster. If the target Kafka cluster does not have Private Network add-on, the endpoint only accepts vpcType of VPC_PEERED;  If the target Kafka cluster has the Private Network add-on, the endpoint accepts vpcTypes of VPC_PEERED and KAFKA_VPC.
	VpcType string `json:"vpcType,omitempty"`

	// Base64 encoded version of the TLS trust store (in JKS format) used to connect to your Kafka Cluster. Only required if connecting to a Non-Instaclustr managed Kafka Cluster with TLS enabled.
	Truststore *os.File `json:"truststore,omitempty"`

	// <b>AWS ONLY</b>. Access information for the S3 bucket where you will store your custom connectors.
	AwsAccessKeyId string `json:"aws.access.key.id,omitempty"`

	// <b>AWS ONLY</b>. Access information for the S3 bucket where you will store your custom connectors.
	AwsSecretAccessKey string `json:"aws.secret.access.key,omitempty"`

	// <b>AWS ONLY</b>. Access information for the S3 bucket where you will store your custom connectors.
	AwsS3RoleArn string `json:"aws.s3.role.arn,omitempty"`

	// <b>AWS ONLY</b>. Access information for the S3 bucket where you will store your custom connectors.
	S3BucketName string `json:"s3.bucket.name,omitempty"`

	// <b>AZURE ONLY</b>. Access information for the Azure Storage container where you will store your custom connectors.
	AzureStorageAccountName string `json:"azure.storage.account.name,omitempty"`

	// <b>AZURE ONLY</b>. Access information for the Azure Storage container where you will store your custom connectors.
	AzureStorageAccountKey string `json:"azure.storage.account.key,omitempty"`

	// <b>AZURE ONLY</b>. Access information for the Azure Storage container where you will store your custom connectors.
	AzureStorageContainerName string `json:"azure.storage.container.name,omitempty"`
}

// AssertKafkaConnectOptionsSchemaRequired checks if the required fields are not zero-ed
func AssertKafkaConnectOptionsSchemaRequired(obj KafkaConnectOptionsSchema) error {
	return nil
}

// AssertKafkaConnectOptionsSchemaConstraints checks if the values respects the defined constraints
func AssertKafkaConnectOptionsSchemaConstraints(obj KafkaConnectOptionsSchema) error {
	return nil
}
