/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ReplaceNodeOperation struct {
	Id string `json:"id,omitempty"`

	Status string `json:"status,omitempty"`

	Node string `json:"node,omitempty"`

	Replacement string `json:"replacement,omitempty"`

	Params ReplaceNodeOperationParams `json:"params,omitempty"`

	ResizeOp string `json:"resizeOp,omitempty"`

	Created time.Time `json:"created,omitempty"`

	Modified time.Time `json:"modified,omitempty"`

	BackupTriggered time.Time `json:"backupTriggered,omitempty"`

	BackupCompleted time.Time `json:"backupCompleted,omitempty"`

	RestoreCompleted time.Time `json:"restoreCompleted,omitempty"`

	FailedStatus string `json:"failedStatus,omitempty"`

	Restore string `json:"restore,omitempty"`

	Details string `json:"details,omitempty"`

	TechopsAlerted time.Time `json:"techopsAlerted,omitempty"`

	AddedDisk string `json:"addedDisk,omitempty"`
}

// AssertReplaceNodeOperationRequired checks if the required fields are not zero-ed
func AssertReplaceNodeOperationRequired(obj ReplaceNodeOperation) error {
	if err := AssertReplaceNodeOperationParamsRequired(obj.Params); err != nil {
		return err
	}
	return nil
}

// AssertReplaceNodeOperationConstraints checks if the values respects the defined constraints
func AssertReplaceNodeOperationConstraints(obj ReplaceNodeOperation) error {
	return nil
}
