/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaUserSummariesV2 - A listable data source of all Kafka users within a Kafka Cluster.
type KafkaUserSummariesV2 struct {

	// ID of the kafka cluster
	ClusterId string `json:"clusterId,omitempty"`

	// List of all Kafka users in the cluster.
	KafkaUsers []KafkaUserSummaryV2 `json:"kafkaUsers,omitempty"`
}

// AssertKafkaUserSummariesV2Required checks if the required fields are not zero-ed
func AssertKafkaUserSummariesV2Required(obj KafkaUserSummariesV2) error {
	for _, el := range obj.KafkaUsers {
		if err := AssertKafkaUserSummaryV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertKafkaUserSummariesV2Constraints checks if the values respects the defined constraints
func AssertKafkaUserSummariesV2Constraints(obj KafkaUserSummariesV2) error {
	return nil
}
