/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PostgresqlReloadOperationV2 - PostgreSQL reload operation.
type PostgresqlReloadOperationV2 struct {

	// Reload operations Id.
	OperationId string `json:"operationId,omitempty"`

	// Reload operation time created.
	TimeCreated string `json:"timeCreated,omitempty"`

	// Reload operation message.
	Message string `json:"message,omitempty"`

	// Node Id of the node in which this reload operation was executed.
	NodeId string `json:"nodeId,omitempty"`

	// Reload operation time modified.
	TimeModified string `json:"timeModified,omitempty"`

	// Reload operation status.
	Status string `json:"status,omitempty"`
}

// AssertPostgresqlReloadOperationV2Required checks if the required fields are not zero-ed
func AssertPostgresqlReloadOperationV2Required(obj PostgresqlReloadOperationV2) error {
	return nil
}

// AssertPostgresqlReloadOperationV2Constraints checks if the values respects the defined constraints
func AssertPostgresqlReloadOperationV2Constraints(obj PostgresqlReloadOperationV2) error {
	return nil
}
