/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ClusterDataCentreRestoreConfigV2 - Definition of a Cluster Data Centre to Cluster Restore
type ClusterDataCentreRestoreConfigV2 struct {
	CustomVpcSettings CustomVpcSettingsRestoreV2 `json:"customVpcSettings,omitempty"`

	// Determines the target VPC for restored cluster. Accepted values are: <ul> <li>NEW_VPC - restores the cluster to a new VPC. Default value if the Cluster Data Centre is omitted in the request.</li> <li>SAME_VPC - restores the cluster to the same VPC as the original cluster, for customers running in their own account.</li> <li>CUSTOM_VPC - restores the cluster to a custom VPC for customers running in their own account.</li> </ul>  CUSTOM_VPC and SAME_VPC options are available only for customers running in their own account.
	RestoreMode string `json:"restoreMode"`

	// Cluster Data Centre ID
	CdcId string `json:"cdcId"`
}

// AssertClusterDataCentreRestoreConfigV2Required checks if the required fields are not zero-ed
func AssertClusterDataCentreRestoreConfigV2Required(obj ClusterDataCentreRestoreConfigV2) error {
	elements := map[string]interface{}{
		"restoreMode": obj.RestoreMode,
		"cdcId":       obj.CdcId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCustomVpcSettingsRestoreV2Required(obj.CustomVpcSettings); err != nil {
		return err
	}
	return nil
}

// AssertClusterDataCentreRestoreConfigV2Constraints checks if the values respects the defined constraints
func AssertClusterDataCentreRestoreConfigV2Constraints(obj ClusterDataCentreRestoreConfigV2) error {
	return nil
}
