/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OperationStatusV2 string

// List of OperationStatusV2
const (
	GENESIS OperationStatusV2 = "GENESIS"
	//RUNNING   OperationStatusV2 = "RUNNING"
	COMPLETED OperationStatusV2 = "COMPLETED"
	CANCELLED OperationStatusV2 = "CANCELLED"
	FAILED    OperationStatusV2 = "FAILED"
)

// AssertOperationStatusV2Required checks if the required fields are not zero-ed
func AssertOperationStatusV2Required(obj OperationStatusV2) error {
	return nil
}

// AssertOperationStatusV2Constraints checks if the values respects the defined constraints
func AssertOperationStatusV2Constraints(obj OperationStatusV2) error {
	return nil
}
