/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ResizeClusterDataCentreOperation struct {
	Id string `json:"id,omitempty"`

	Cdc string `json:"cdc,omitempty"`

	Params ResizeCdcOperationParams `json:"params,omitempty"`

	Created time.Time `json:"created,omitempty"`

	Completed time.Time `json:"completed,omitempty"`

	Provider string `json:"provider,omitempty"`

	DataCentre string `json:"dataCentre,omitempty"`

	CompletedStatus string `json:"completedStatus,omitempty"`

	NotifyContacts string `json:"notifyContacts,omitempty"`

	ReplaceOps []ReplaceNodeOperation `json:"replaceOps,omitempty"`

	SkipInitialCheck bool `json:"skipInitialCheck,omitempty"`

	Details string `json:"details,omitempty"`

	TechopsAlerted time.Time `json:"techopsAlerted,omitempty"`

	FirstStateHealthCheckFailure time.Time `json:"firstStateHealthCheckFailure,omitempty"`

	InitiatedBy string `json:"initiatedBy,omitempty"`

	IgnoreFeatureState bool `json:"ignoreFeatureState,omitempty"`

	RiemaintRuleIds []string `json:"riemaintRuleIds,omitempty"`

	SshMessageId string `json:"sshMessageId,omitempty"`
}

// AssertResizeClusterDataCentreOperationRequired checks if the required fields are not zero-ed
func AssertResizeClusterDataCentreOperationRequired(obj ResizeClusterDataCentreOperation) error {
	if err := AssertResizeCdcOperationParamsRequired(obj.Params); err != nil {
		return err
	}
	for _, el := range obj.ReplaceOps {
		if err := AssertReplaceNodeOperationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertResizeClusterDataCentreOperationConstraints checks if the values respects the defined constraints
func AssertResizeClusterDataCentreOperationConstraints(obj ResizeClusterDataCentreOperation) error {
	return nil
}
