/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaUserSummariesV2 - A listable data source of all Kafka users within a Kafka Cluster.
type KafkaUserSummariesV2 struct {

	// ID of the kafka cluster
	ClusterId string `json:"clusterId,omitempty"`

	// List of all Kafka users in the cluster.
	KafkaUsers []KafkaUserSummaryV2 `json:"kafkaUsers,omitempty"`
}

// AssertKafkaUserSummariesV2Required checks if the required fields are not zero-ed
func AssertKafkaUserSummariesV2Required(obj KafkaUserSummariesV2) error {
	for _, el := range obj.KafkaUsers {
		if err := AssertKafkaUserSummaryV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseKafkaUserSummariesV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of KafkaUserSummariesV2 (e.g. [][]KafkaUserSummariesV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseKafkaUserSummariesV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aKafkaUserSummariesV2, ok := obj.(KafkaUserSummariesV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertKafkaUserSummariesV2Required(aKafkaUserSummariesV2)
	})
}
