/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccountClustersV2 - A listable data source of all cluster IDs in an Instaclustr Account.
type AccountClustersV2 struct {

	// UUID of the Instaclustr Account.
	AccountId string `json:"accountId,omitempty"`

	//
	Clusters []ClusterSummaryV2 `json:"clusters,omitempty"`
}

// AssertAccountClustersV2Required checks if the required fields are not zero-ed
func AssertAccountClustersV2Required(obj AccountClustersV2) error {
	for _, el := range obj.Clusters {
		if err := AssertClusterSummaryV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseAccountClustersV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AccountClustersV2 (e.g. [][]AccountClustersV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAccountClustersV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAccountClustersV2, ok := obj.(AccountClustersV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAccountClustersV2Required(aAccountClustersV2)
	})
}
