/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// IamPrincipalArnV2 - Definition of an IAM Principal ARN being used for Kafka PrivateLink.
type IamPrincipalArnV2 struct {

	// The ID of the cluster data center.
	ClusterDataCenterId string `json:"clusterDataCenterId"`

	// The Instaclustr ID of the AWS endpoint service
	EndPointServiceId string `json:"endPointServiceId,omitempty"`

	// The Instaclustr ID of the IAM Principal ARN.
	Id string `json:"id,omitempty"`

	// The IAM Principal ARN.
	PrincipalArn string `json:"principalArn"`
}

// AssertIamPrincipalArnV2Required checks if the required fields are not zero-ed
func AssertIamPrincipalArnV2Required(obj IamPrincipalArnV2) error {
	elements := map[string]interface{}{
		"clusterDataCenterId": obj.ClusterDataCenterId,
		"principalArn":        obj.PrincipalArn,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIamPrincipalArnV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IamPrincipalArnV2 (e.g. [][]IamPrincipalArnV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIamPrincipalArnV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIamPrincipalArnV2, ok := obj.(IamPrincipalArnV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIamPrincipalArnV2Required(aIamPrincipalArnV2)
	})
}
