/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GcpApiPeeringConnectionWithRemoteInfo struct {

	// ID of the VPC peering connection
	Id string `json:"id,omitempty"`

	// Name of the Vpc Peering Connection
	Name string `json:"name,omitempty"`

	// Vpc Network Name of the Datacenter VPC
	VpcNetworkName string `json:"vpcNetworkName,omitempty"`

	// Vpc Network Name of the Peered VPC
	PeerVpcNetworkName string `json:"peerVpcNetworkName,omitempty"`

	// GCP Project ID of the Datacenter
	ProjectId string `json:"projectId,omitempty"`

	// GCP Project ID of the Peered VPC
	PeerProjectId string `json:"peerProjectId,omitempty"`

	// ID of the Cluster Data Centre
	ClusterDataCentre string `json:"clusterDataCentre,omitempty"`

	PeerSubnets AzureApiPeeringConnectionPeerSubnets `json:"peerSubnets,omitempty"`

	// Reason for Peering Connection Failure
	FailureReason string `json:"failureReason,omitempty"`

	// Status of the VPC peering connection
	StatusCode string `json:"statusCode,omitempty"`
}

// AssertGcpApiPeeringConnectionWithRemoteInfoRequired checks if the required fields are not zero-ed
func AssertGcpApiPeeringConnectionWithRemoteInfoRequired(obj GcpApiPeeringConnectionWithRemoteInfo) error {
	if err := AssertAzureApiPeeringConnectionPeerSubnetsRequired(obj.PeerSubnets); err != nil {
		return err
	}
	return nil
}

// AssertGcpApiPeeringConnectionWithRemoteInfoConstraints checks if the values respects the defined constraints
func AssertGcpApiPeeringConnectionWithRemoteInfoConstraints(obj GcpApiPeeringConnectionWithRemoteInfo) error {
	return nil
}
