/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FirewallRuleKind struct {
	Type string `json:"type"`

	// The provisioning status of the firewall.
	Status string `json:"status,omitempty"`

	// The reason for deferral, if the provisioning status of this firewall rule is deferred.
	DeferredReason string `json:"deferredReason,omitempty"`
}

// AssertFirewallRuleKindRequired checks if the required fields are not zero-ed
func AssertFirewallRuleKindRequired(obj FirewallRuleKind) error {
	elements := map[string]interface{}{
		"type": obj.Type,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertFirewallRuleKindConstraints checks if the values respects the defined constraints
func AssertFirewallRuleKindConstraints(obj FirewallRuleKind) error {
	return nil
}
