/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PrivateLink - Creates a PrivateLink cluster, see <a href=\"https://www.instaclustr.com/support/documentation/useful-information/privatelink/\" target=\"_blank\">PrivateLink</a>    PrivateLink can only be supported on AWS_VPC for Kafka.
type PrivateLink struct {

	// List of IAM Principal ARNs to add to the endpoint service.
	IamPrincipalARNs []string `json:"iamPrincipalARNs,omitempty"`
}

// AssertPrivateLinkRequired checks if the required fields are not zero-ed
func AssertPrivateLinkRequired(obj PrivateLink) error {
	return nil
}

// AssertPrivateLinkConstraints checks if the values respects the defined constraints
func AssertPrivateLinkConstraints(obj PrivateLink) error {
	return nil
}
