/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PgBouncerOptionsSchema struct {

	// PgBouncer pooling mode
	PoolMode string `json:"poolMode,omitempty"`
}

// AssertPgBouncerOptionsSchemaRequired checks if the required fields are not zero-ed
func AssertPgBouncerOptionsSchemaRequired(obj PgBouncerOptionsSchema) error {
	return nil
}

// AssertPgBouncerOptionsSchemaConstraints checks if the values respects the defined constraints
func AssertPgBouncerOptionsSchemaConstraints(obj PgBouncerOptionsSchema) error {
	return nil
}
