/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ModifyAwsEndpointServicePrincipalsRequest struct {

	// List of IAM Principal ARNs to add to AWS Endpoint Service
	PrincipalsToAdd []string `json:"principalsToAdd,omitempty"`

	// List of IAM Principal ARNs to remove from AWS Endpoint Service
	PrincipalsToRemove []string `json:"principalsToRemove,omitempty"`

	ValidationMessages map[string]string `json:"validationMessages,omitempty"`
}

// AssertModifyAwsEndpointServicePrincipalsRequestRequired checks if the required fields are not zero-ed
func AssertModifyAwsEndpointServicePrincipalsRequestRequired(obj ModifyAwsEndpointServicePrincipalsRequest) error {
	return nil
}

// AssertModifyAwsEndpointServicePrincipalsRequestConstraints checks if the values respects the defined constraints
func AssertModifyAwsEndpointServicePrincipalsRequestConstraints(obj ModifyAwsEndpointServicePrincipalsRequest) error {
	return nil
}
