/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type KafkaConnectCustomConnectorsGcpV2 struct {

	// Access information for the GCP Storage bucket for kafka connect custom connectors.
	PrivateKey string `json:"privateKey"`

	// Access information for the GCP Storage bucket for kafka connect custom connectors.
	ClientId string `json:"clientId"`

	// Access information for the GCP Storage bucket for kafka connect custom connectors.
	ClientEmail string `json:"clientEmail"`

	// Access information for the GCP Storage bucket for kafka connect custom connectors.
	ProjectId string `json:"projectId"`

	// Access information for the GCP Storage bucket for kafka connect custom connectors.
	StorageBucketName string `json:"storageBucketName"`

	// Access information for the GCP Storage bucket for kafka connect custom connectors.
	PrivateKeyId string `json:"privateKeyId"`
}

// AssertKafkaConnectCustomConnectorsGcpV2Required checks if the required fields are not zero-ed
func AssertKafkaConnectCustomConnectorsGcpV2Required(obj KafkaConnectCustomConnectorsGcpV2) error {
	elements := map[string]interface{}{
		"privateKey":        obj.PrivateKey,
		"clientId":          obj.ClientId,
		"clientEmail":       obj.ClientEmail,
		"projectId":         obj.ProjectId,
		"storageBucketName": obj.StorageBucketName,
		"privateKeyId":      obj.PrivateKeyId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKafkaConnectCustomConnectorsGcpV2Constraints checks if the values respects the defined constraints
func AssertKafkaConnectCustomConnectorsGcpV2Constraints(obj KafkaConnectCustomConnectorsGcpV2) error {
	return nil
}
