/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type KafkaKraftSettingsV2 struct {

	// Number of KRaft controller nodes (only 3 is currently supported).
	ControllerNodeCount int32 `json:"controllerNodeCount"`
}

// AssertKafkaKraftSettingsV2Required checks if the required fields are not zero-ed
func AssertKafkaKraftSettingsV2Required(obj KafkaKraftSettingsV2) error {
	elements := map[string]interface{}{
		"controllerNodeCount": obj.ControllerNodeCount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKafkaKraftSettingsV2Constraints checks if the values respects the defined constraints
func AssertKafkaKraftSettingsV2Constraints(obj KafkaKraftSettingsV2) error {
	return nil
}
