/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaTopicNamesV2 - Definition of Kafka Topic names in the Kafka cluster
type KafkaTopicNamesV2 struct {

	// List of Kafka topic names
	TopicNames []string `json:"topicNames,omitempty"`

	// ID of the Kafka cluster
	ClusterId string `json:"clusterId,omitempty"`
}

// AssertKafkaTopicNamesV2Required checks if the required fields are not zero-ed
func AssertKafkaTopicNamesV2Required(obj KafkaTopicNamesV2) error {
	return nil
}

// AssertKafkaTopicNamesV2Constraints checks if the values respects the defined constraints
func AssertKafkaTopicNamesV2Constraints(obj KafkaTopicNamesV2) error {
	return nil
}
