/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CreateServiceUserRequest - Defines all the details required to add a service user.
type CreateServiceUserRequest struct {

	// Username of the service user. must be unique.
	Username string `json:"username"`

	// Email of the service user. must be unique (including aliases)
	Email string `json:"email"`

	// Profile of the service user OWNER can manage clusters and users (excluding other service users) CLUSTER_ADMIN can manage clusters READ_ONLY can view clusters and access monitoring
	Profile string `json:"profile"`

	// Display name of the service user
	DisplayName string `json:"displayName,omitempty"`

	ValidationMessages map[string]string `json:"validationMessages,omitempty"`
}

// AssertCreateServiceUserRequestRequired checks if the required fields are not zero-ed
func AssertCreateServiceUserRequestRequired(obj CreateServiceUserRequest) error {
	elements := map[string]interface{}{
		"username": obj.Username,
		"email":    obj.Email,
		"profile":  obj.Profile,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateServiceUserRequestConstraints checks if the values respects the defined constraints
func AssertCreateServiceUserRequestConstraints(obj CreateServiceUserRequest) error {
	return nil
}
