/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EncryptionKeyValidationResponse struct {

	// The Response message from the API stating if the key is valid
	Message string `json:"message,omitempty"`

	// If the key is valid or invalid
	IsValid bool `json:"isValid,omitempty"`

	Regions []Region `json:"regions,omitempty"`
}

// AssertEncryptionKeyValidationResponseRequired checks if the required fields are not zero-ed
func AssertEncryptionKeyValidationResponseRequired(obj EncryptionKeyValidationResponse) error {
	for _, el := range obj.Regions {
		if err := AssertRegionRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEncryptionKeyValidationResponseConstraints checks if the values respects the defined constraints
func AssertEncryptionKeyValidationResponseConstraints(obj EncryptionKeyValidationResponse) error {
	return nil
}
