/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MaintenanceEventScheduleResponse struct {

	// Unique Id for this maintenance event
	Id string `json:"id,omitempty"`

	// Unique Id for the cluster that this maintenance event relates to
	ClusterId string `json:"clusterId,omitempty"`

	// A text description of the activities being performed in this maintenance event
	Description string `json:"description,omitempty"`

	// The time this maintenance event is scheduled to start in UTC time
	ScheduledStartTime string `json:"scheduledStartTime,omitempty"`

	// The time this maintenance event is scheduled to end by in UTC time
	ScheduledEndTime string `json:"scheduledEndTime,omitempty"`

	// The earliest limit for the scheduled start time in UTC time, i.e., scheduled start time will be after this value
	ScheduledStartTimeMin string `json:"scheduledStartTimeMin,omitempty"`

	// The latest limit for the scheduled start time in UTC time, i.e., scheduled start time will be before this value
	ScheduledStartTimeMax string `json:"scheduledStartTimeMax,omitempty"`

	// Whether or not we can still allow the event to be rescheduled
	IsFinalized bool `json:"isFinalized,omitempty"`
}

// AssertMaintenanceEventScheduleResponseRequired checks if the required fields are not zero-ed
func AssertMaintenanceEventScheduleResponseRequired(obj MaintenanceEventScheduleResponse) error {
	return nil
}

// AssertMaintenanceEventScheduleResponseConstraints checks if the values respects the defined constraints
func AssertMaintenanceEventScheduleResponseConstraints(obj MaintenanceEventScheduleResponse) error {
	return nil
}
