/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ProviderAwsSettingsV2 -
type ProviderAwsSettingsV2 struct {

	// ID of a KMS encryption key to encrypt data on nodes. KMS encryption key must be set in Cluster Resources through the Instaclustr Console before provisioning an encrypted Data Centre.
	EbsEncryptionKey string `json:"ebsEncryptionKey,omitempty"`

	// VPC ID into which the Data Centre will be provisioned. The Data Centre's network allocation must match the IPv4 CIDR block of the specified VPC.
	CustomVirtualNetworkId string `json:"customVirtualNetworkId,omitempty"`
}

// AssertProviderAwsSettingsV2Required checks if the required fields are not zero-ed
func AssertProviderAwsSettingsV2Required(obj ProviderAwsSettingsV2) error {
	return nil
}

// AssertRecurseProviderAwsSettingsV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ProviderAwsSettingsV2 (e.g. [][]ProviderAwsSettingsV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseProviderAwsSettingsV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aProviderAwsSettingsV2, ok := obj.(ProviderAwsSettingsV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertProviderAwsSettingsV2Required(aProviderAwsSettingsV2)
	})
}
