/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CadenceClusterUpdateV2 -
type CadenceClusterUpdateV2 struct {

	// List of data centre settings.
	DataCentres []CadenceDataCentreV2 `json:"dataCentres"`
}

// AssertCadenceClusterUpdateV2Required checks if the required fields are not zero-ed
func AssertCadenceClusterUpdateV2Required(obj CadenceClusterUpdateV2) error {
	elements := map[string]interface{}{
		"dataCentres": obj.DataCentres,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.DataCentres {
		if err := AssertCadenceDataCentreV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseCadenceClusterUpdateV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CadenceClusterUpdateV2 (e.g. [][]CadenceClusterUpdateV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCadenceClusterUpdateV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCadenceClusterUpdateV2, ok := obj.(CadenceClusterUpdateV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCadenceClusterUpdateV2Required(aCadenceClusterUpdateV2)
	})
}
