/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KarapaceSchemaRegistryUserSummaryV2 - Summary of a Karapace Schema Registry User to be applied to a Kafka cluster.
type KarapaceSchemaRegistryUserSummaryV2 struct {

	// ID of the Kafka cluster.
	ClusterId string `json:"clusterId"`

	// Instaclustr identifier for the Karapace Schema Registry user. The value of this property has the form: [cluster-id]_[karapace-schema-registry-username]
	Id string `json:"id,omitempty"`

	// Username of the Karapace Schema Registry user.
	Username string `json:"username"`
}

// AssertKarapaceSchemaRegistryUserSummaryV2Required checks if the required fields are not zero-ed
func AssertKarapaceSchemaRegistryUserSummaryV2Required(obj KarapaceSchemaRegistryUserSummaryV2) error {
	elements := map[string]interface{}{
		"clusterId": obj.ClusterId,
		"username":  obj.Username,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKarapaceSchemaRegistryUserSummaryV2Constraints checks if the values respects the defined constraints
func AssertKarapaceSchemaRegistryUserSummaryV2Constraints(obj KarapaceSchemaRegistryUserSummaryV2) error {
	return nil
}
