/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SecurityGroupFirewallRuleSchema struct {
	Rules []FirewallRuleKind `json:"rules"`

	// The security group to which the firewall rule relates.  Should not be included if network is already included.
	SecurityGroupId string `json:"securityGroupId,omitempty"`
}

// AssertSecurityGroupFirewallRuleSchemaRequired checks if the required fields are not zero-ed
func AssertSecurityGroupFirewallRuleSchemaRequired(obj SecurityGroupFirewallRuleSchema) error {
	elements := map[string]interface{}{
		"rules": obj.Rules,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Rules {
		if err := AssertFirewallRuleKindRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertSecurityGroupFirewallRuleSchemaConstraints checks if the values respects the defined constraints
func AssertSecurityGroupFirewallRuleSchemaConstraints(obj SecurityGroupFirewallRuleSchema) error {
	return nil
}
