/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AzureVnetPeerV2 - Definition of an Azure Virtual Network Peering request to allow privately routed connections to a target data centre.
type AzureVnetPeerV2 struct {

	// The name of the VPC Network you wish to peer to.
	PeerVirtualNetworkName string `json:"peerVirtualNetworkName"`

	// The subnets for the peering VPC.
	PeerSubnets []string `json:"peerSubnets"`

	// Reason for Peering Connection Failure.
	FailureReason string `json:"failureReason,omitempty"`

	// Name of the Vpc Peering Connection.
	Name string `json:"name,omitempty"`

	// ID of the Active Directory Object to give peering permissions to, required for cross subscription peering.
	PeerAdObjectId string `json:"peerAdObjectId,omitempty"`

	// ID of the VPC peering connection.
	Id string `json:"id,omitempty"`

	// Resource Group Name of the Virtual Network.
	PeerResourceGroup string `json:"peerResourceGroup"`

	// Subscription ID of the Virtual Network.
	PeerSubscriptionId string `json:"peerSubscriptionId"`

	// Status of the VPC Peering Connection. Values can be `GENESIS`, `PROVISIONING`, `FAILED`, `INACTIVE`, `CONNECTED` or `UNKNOWN`.
	StatusCode string `json:"statusCode,omitempty"`

	// ID of the Cluster Data Centre.
	CdcId string `json:"cdcId"`
}

// AssertAzureVnetPeerV2Required checks if the required fields are not zero-ed
func AssertAzureVnetPeerV2Required(obj AzureVnetPeerV2) error {
	elements := map[string]interface{}{
		"peerVirtualNetworkName": obj.PeerVirtualNetworkName,
		"peerSubnets":            obj.PeerSubnets,
		"peerResourceGroup":      obj.PeerResourceGroup,
		"peerSubscriptionId":     obj.PeerSubscriptionId,
		"cdcId":                  obj.CdcId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseAzureVnetPeerV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AzureVnetPeerV2 (e.g. [][]AzureVnetPeerV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAzureVnetPeerV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAzureVnetPeerV2, ok := obj.(AzureVnetPeerV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAzureVnetPeerV2Required(aAzureVnetPeerV2)
	})
}
