/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaRestProxyUserSummaryV2 - Summary of a Kafka Rest Proxy User to be applied to a Kafka cluster.
type KafkaRestProxyUserSummaryV2 struct {

	// ID of the Kafka cluster.
	ClusterId string `json:"clusterId"`

	// Instaclustr identifier for the Kafka Rest Proxy user. The value of this property has the form: [cluster-id]_[kafka-rest-proxy-username]
	Id string `json:"id,omitempty"`

	// Username of the Kafka Rest Proxy user.
	Username string `json:"username"`
}

// AssertKafkaRestProxyUserSummaryV2Required checks if the required fields are not zero-ed
func AssertKafkaRestProxyUserSummaryV2Required(obj KafkaRestProxyUserSummaryV2) error {
	elements := map[string]interface{}{
		"clusterId": obj.ClusterId,
		"username":  obj.Username,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKafkaRestProxyUserSummaryV2Constraints checks if the values respects the defined constraints
func AssertKafkaRestProxyUserSummaryV2Constraints(obj KafkaRestProxyUserSummaryV2) error {
	return nil
}
