/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateCustomSourceMirrorRequestSchemaOnlyClass struct {

	// Indicates that your source cluster is a custom cluster
	SourceType string `json:"sourceType,omitempty"`

	// Whether to rename topics as they are mirrored, by prefixing the source alias to the topic name
	UseRenaming bool `json:"useRenaming,omitempty"`

	// alias to use for your source kafka cluster. This will be used to rename topics if that option is turned on
	SourceAlias string `json:"sourceAlias,omitempty"`

	// Kafka connection properties used to connect to your source cluster
	SourceConnectionProperties string `json:"sourceConnectionProperties,omitempty"`

	// Regex to select which topics to mirror
	TopicsRegex string `json:"topicsRegex,omitempty"`

	// Maximum number of tasks for Kafka Connect to use
	MaxTasks int32 `json:"maxTasks,omitempty"`
}

// AssertCreateCustomSourceMirrorRequestSchemaOnlyClassRequired checks if the required fields are not zero-ed
func AssertCreateCustomSourceMirrorRequestSchemaOnlyClassRequired(obj CreateCustomSourceMirrorRequestSchemaOnlyClass) error {
	return nil
}

// AssertCreateCustomSourceMirrorRequestSchemaOnlyClassConstraints checks if the values respects the defined constraints
func AssertCreateCustomSourceMirrorRequestSchemaOnlyClassConstraints(obj CreateCustomSourceMirrorRequestSchemaOnlyClass) error {
	return nil
}
