/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BundleUserDeleteRequest struct {
	Username string `json:"username"`
}

// AssertBundleUserDeleteRequestRequired checks if the required fields are not zero-ed
func AssertBundleUserDeleteRequestRequired(obj BundleUserDeleteRequest) error {
	elements := map[string]interface{}{
		"username": obj.Username,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseBundleUserDeleteRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BundleUserDeleteRequest (e.g. [][]BundleUserDeleteRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBundleUserDeleteRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBundleUserDeleteRequest, ok := obj.(BundleUserDeleteRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBundleUserDeleteRequestRequired(aBundleUserDeleteRequest)
	})
}
