/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaAclListsV2 - List of access control lists for a Kafka cluster.
type KafkaAclListsV2 struct {

	// UUID of the Kafka cluster
	ClusterId string `json:"clusterId,omitempty"`

	// List of all ACLs in the Kafka cluster.
	AclLists []KafkaAclListV2 `json:"aclLists,omitempty"`
}

// AssertKafkaAclListsV2Required checks if the required fields are not zero-ed
func AssertKafkaAclListsV2Required(obj KafkaAclListsV2) error {
	for _, el := range obj.AclLists {
		if err := AssertKafkaAclListV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseKafkaAclListsV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of KafkaAclListsV2 (e.g. [][]KafkaAclListsV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseKafkaAclListsV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aKafkaAclListsV2, ok := obj.(KafkaAclListsV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertKafkaAclListsV2Required(aKafkaAclListsV2)
	})
}
