/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CassandraClusterUpdateV2 struct {

	// List of datacentre settings.
	DataCentres []CassandraDataCentreV2 `json:"dataCentres"`

	// A description of the cluster
	Description string `json:"description,omitempty"`

	TwoFactorDelete []TwoFactorDeleteSettingsV2 `json:"twoFactorDelete,omitempty"`

	// Settings to determine how resize requests will be performed for the cluster.
	ResizeSettings []ResizeSettingsV2 `json:"resizeSettings,omitempty"`
}

// AssertCassandraClusterUpdateV2Required checks if the required fields are not zero-ed
func AssertCassandraClusterUpdateV2Required(obj CassandraClusterUpdateV2) error {
	elements := map[string]interface{}{
		"dataCentres": obj.DataCentres,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.DataCentres {
		if err := AssertCassandraDataCentreV2Required(el); err != nil {
			return err
		}
	}
	for _, el := range obj.TwoFactorDelete {
		if err := AssertTwoFactorDeleteSettingsV2Required(el); err != nil {
			return err
		}
	}
	for _, el := range obj.ResizeSettings {
		if err := AssertResizeSettingsV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCassandraClusterUpdateV2Constraints checks if the values respects the defined constraints
func AssertCassandraClusterUpdateV2Constraints(obj CassandraClusterUpdateV2) error {
	return nil
}
