/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FirewallRule struct {
	Network string `json:"network,omitempty"`

	SecurityGroupId string `json:"securityGroupId,omitempty"`

	Rules []FirewallRuleKind `json:"rules"`
}

// AssertFirewallRuleRequired checks if the required fields are not zero-ed
func AssertFirewallRuleRequired(obj FirewallRule) error {
	elements := map[string]interface{}{
		"rules": obj.Rules,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Rules {
		if err := AssertFirewallRuleKindRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertFirewallRuleConstraints checks if the values respects the defined constraints
func AssertFirewallRuleConstraints(obj FirewallRule) error {
	return nil
}
