/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CloudProviderEnumV2 : Name of the cloud provider service in which the Data Centre will be provisioned.
type CloudProviderEnumV2 string

// List of CloudProviderEnumV2
const (
	AWS_VPC  CloudProviderEnumV2 = "AWS_VPC"
	GCP      CloudProviderEnumV2 = "GCP"
	AZURE    CloudProviderEnumV2 = "AZURE"
	AZURE_AZ CloudProviderEnumV2 = "AZURE_AZ"
)

// AssertCloudProviderEnumV2Required checks if the required fields are not zero-ed
func AssertCloudProviderEnumV2Required(obj CloudProviderEnumV2) error {
	return nil
}

// AssertRecurseCloudProviderEnumV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CloudProviderEnumV2 (e.g. [][]CloudProviderEnumV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCloudProviderEnumV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCloudProviderEnumV2, ok := obj.(CloudProviderEnumV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCloudProviderEnumV2Required(aCloudProviderEnumV2)
	})
}
