/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CadenceSharedProvisioningV2 - Settings for SHARED provisioning
type CadenceSharedProvisioningV2 struct {

	// Use Advanced Visibility
	UseAdvancedVisibility bool `json:"useAdvancedVisibility"`
}

// AssertCadenceSharedProvisioningV2Required checks if the required fields are not zero-ed
func AssertCadenceSharedProvisioningV2Required(obj CadenceSharedProvisioningV2) error {
	elements := map[string]interface{}{
		"useAdvancedVisibility": obj.UseAdvancedVisibility,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCadenceSharedProvisioningV2Constraints checks if the values respects the defined constraints
func AssertCadenceSharedProvisioningV2Constraints(obj CadenceSharedProvisioningV2) error {
	return nil
}
