/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaAclListsV2 - List of access control lists for a Kafka cluster.
type KafkaAclListsV2 struct {

	// UUID of the Kafka cluster
	ClusterId string `json:"clusterId,omitempty"`

	// List of all ACLs in the Kafka cluster.
	AclLists []KafkaAclListV2 `json:"aclLists,omitempty"`
}

// AssertKafkaAclListsV2Required checks if the required fields are not zero-ed
func AssertKafkaAclListsV2Required(obj KafkaAclListsV2) error {
	for _, el := range obj.AclLists {
		if err := AssertKafkaAclListV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertKafkaAclListsV2Constraints checks if the values respects the defined constraints
func AssertKafkaAclListsV2Constraints(obj KafkaAclListsV2) error {
	return nil
}
