/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type KafkaConnectClusterUpdateV2 struct {

	// List of datacentre settings.
	DataCentres []KafkaConnectDataCentreV2 `json:"dataCentres"`

	// A description of the cluster
	Description string `json:"description,omitempty"`

	TwoFactorDelete []TwoFactorDeleteSettingsV2 `json:"twoFactorDelete,omitempty"`
}

// AssertKafkaConnectClusterUpdateV2Required checks if the required fields are not zero-ed
func AssertKafkaConnectClusterUpdateV2Required(obj KafkaConnectClusterUpdateV2) error {
	elements := map[string]interface{}{
		"dataCentres": obj.DataCentres,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.DataCentres {
		if err := AssertKafkaConnectDataCentreV2Required(el); err != nil {
			return err
		}
	}
	for _, el := range obj.TwoFactorDelete {
		if err := AssertTwoFactorDeleteSettingsV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertKafkaConnectClusterUpdateV2Constraints checks if the values respects the defined constraints
func AssertKafkaConnectClusterUpdateV2Constraints(obj KafkaConnectClusterUpdateV2) error {
	return nil
}
