/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccountAwsVpcPeersV2 - A listable data source of all AWS VPC Peering requests in an Instaclustr Account.
type AccountAwsVpcPeersV2 struct {

	// UUID of the Instaclustr Account.
	AccountId string `json:"accountId,omitempty"`

	PeeringRequests []AwsVpcPeerSummaryV2 `json:"peeringRequests,omitempty"`
}

// AssertAccountAwsVpcPeersV2Required checks if the required fields are not zero-ed
func AssertAccountAwsVpcPeersV2Required(obj AccountAwsVpcPeersV2) error {
	for _, el := range obj.PeeringRequests {
		if err := AssertAwsVpcPeerSummaryV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAccountAwsVpcPeersV2Constraints checks if the values respects the defined constraints
func AssertAccountAwsVpcPeersV2Constraints(obj AccountAwsVpcPeersV2) error {
	return nil
}
