/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// OpenSearchEgressRuleSourceV2 : Source OpenSearch plugin that manages the channel/destination
type OpenSearchEgressRuleSourceV2 string

// List of OpenSearchEgressRuleSourceV2
const (
	ALERTING      OpenSearchEgressRuleSourceV2 = "ALERTING"
	NOTIFICATIONS OpenSearchEgressRuleSourceV2 = "NOTIFICATIONS"
)

// AssertOpenSearchEgressRuleSourceV2Required checks if the required fields are not zero-ed
func AssertOpenSearchEgressRuleSourceV2Required(obj OpenSearchEgressRuleSourceV2) error {
	return nil
}

// AssertRecurseOpenSearchEgressRuleSourceV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of OpenSearchEgressRuleSourceV2 (e.g. [][]OpenSearchEgressRuleSourceV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOpenSearchEgressRuleSourceV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOpenSearchEgressRuleSourceV2, ok := obj.(OpenSearchEgressRuleSourceV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOpenSearchEgressRuleSourceV2Required(aOpenSearchEgressRuleSourceV2)
	})
}
