/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NodeDetailsV2 -
type NodeDetailsV2 struct {

	// The roles or purposes of the node. Useful for filtering for nodes that have a specific role.
	NodeRoles []NodeRolesV2 `json:"nodeRoles,omitempty"`

	// Rack name in which the node is located.
	Rack string `json:"rack,omitempty"`

	// Size of the node.
	NodeSize string `json:"nodeSize,omitempty"`

	// Private IP address of the node.
	PrivateAddress string `json:"privateAddress,omitempty"`

	// Public IP address of the node.
	PublicAddress string `json:"publicAddress,omitempty"`

	// ID of the node.
	Id string `json:"id,omitempty"`

	// Provisioning status of the node.
	Status string `json:"status,omitempty"`
}

// AssertNodeDetailsV2Required checks if the required fields are not zero-ed
func AssertNodeDetailsV2Required(obj NodeDetailsV2) error {
	return nil
}

// AssertRecurseNodeDetailsV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NodeDetailsV2 (e.g. [][]NodeDetailsV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNodeDetailsV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNodeDetailsV2, ok := obj.(NodeDetailsV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNodeDetailsV2Required(aNodeDetailsV2)
	})
}
