/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type KafkaKarapaceSchemaRegistryDetailsV2 struct {

	// Adds the specified version of Kafka Schema Registry to the Kafka cluster. Available versions: <ul> <li>`3.4.3`</li> <li>`3.6.2`</li> </ul>
	Version string `json:"version"`
}

// AssertKafkaKarapaceSchemaRegistryDetailsV2Required checks if the required fields are not zero-ed
func AssertKafkaKarapaceSchemaRegistryDetailsV2Required(obj KafkaKarapaceSchemaRegistryDetailsV2) error {
	elements := map[string]interface{}{
		"version": obj.Version,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKafkaKarapaceSchemaRegistryDetailsV2Constraints checks if the values respects the defined constraints
func AssertKafkaKarapaceSchemaRegistryDetailsV2Constraints(obj KafkaKarapaceSchemaRegistryDetailsV2) error {
	return nil
}
