/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type KafkaListenerV2 struct {
	Protocol KafkaListenerProtocolEnumV2 `json:"protocol"`
}

// AssertKafkaListenerV2Required checks if the required fields are not zero-ed
func AssertKafkaListenerV2Required(obj KafkaListenerV2) error {
	elements := map[string]interface{}{
		"protocol": obj.Protocol,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKafkaListenerV2Constraints checks if the values respects the defined constraints
func AssertKafkaListenerV2Constraints(obj KafkaListenerV2) error {
	return nil
}
