/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BundleUserCreateRequest struct {
	Username string `json:"username"`

	// Bundle user password
	Password string `json:"password"`

	// A collection of optional bundle-specific user options - the options available to be set differ depending on the bundle type.</h3><table style=\"width:100%;word-break:break-word;font-size:0.8em\"> <tr><th>Bundle</th><th>Option</th><th>Allowable values</th></tr> <tr><td>Kafka</td><td>\"sasl-scram-mechanism\"</td><td>\"SCRAM-SHA-256\" (Default), \"SCRAM-SHA-512\"</td></tr> <tr><td>Kafka</td><td>\"override-existing-user\"</td><td>true (Default), false</td></tr> </table>
	Options map[string]interface{} `json:"options,omitempty"`

	// Permissions upon user creation
	InitialPermissions string `json:"initial-permissions,omitempty"`
}

// AssertBundleUserCreateRequestRequired checks if the required fields are not zero-ed
func AssertBundleUserCreateRequestRequired(obj BundleUserCreateRequest) error {
	elements := map[string]interface{}{
		"username": obj.Username,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseBundleUserCreateRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BundleUserCreateRequest (e.g. [][]BundleUserCreateRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBundleUserCreateRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBundleUserCreateRequest, ok := obj.(BundleUserCreateRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBundleUserCreateRequestRequired(aBundleUserCreateRequest)
	})
}
