/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// KafkaConnectMirrorConnectorDetailsV2 - Details of a connector.
type KafkaConnectMirrorConnectorDetailsV2 struct {

	// Name of the connector. Could be one of [Mirror Connector, Checkpoint Connector].
	Name string `json:"name,omitempty"`

	// Configuration of the connector.
	Config string `json:"config,omitempty"`

	// Status of the connector.
	Status string `json:"status,omitempty"`
}

// AssertKafkaConnectMirrorConnectorDetailsV2Required checks if the required fields are not zero-ed
func AssertKafkaConnectMirrorConnectorDetailsV2Required(obj KafkaConnectMirrorConnectorDetailsV2) error {
	return nil
}

// AssertKafkaConnectMirrorConnectorDetailsV2Constraints checks if the values respects the defined constraints
func AssertKafkaConnectMirrorConnectorDetailsV2Constraints(obj KafkaConnectMirrorConnectorDetailsV2) error {
	return nil
}
