/*
 * Instaclustr Cluster Management API
 *
 * Instaclustr Cluster Management API
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CassandraClusterUpdateV2 -
type CassandraClusterUpdateV2 struct {

	// List of datacentre settings.
	DataCentres []CassandraDataCentreV2 `json:"dataCentres"`
}

// AssertCassandraClusterUpdateV2Required checks if the required fields are not zero-ed
func AssertCassandraClusterUpdateV2Required(obj CassandraClusterUpdateV2) error {
	elements := map[string]interface{}{
		"dataCentres": obj.DataCentres,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.DataCentres {
		if err := AssertCassandraDataCentreV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseCassandraClusterUpdateV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CassandraClusterUpdateV2 (e.g. [][]CassandraClusterUpdateV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCassandraClusterUpdateV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCassandraClusterUpdateV2, ok := obj.(CassandraClusterUpdateV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCassandraClusterUpdateV2Required(aCassandraClusterUpdateV2)
	})
}
