/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NodeSize - List of available node sizes
type NodeSize struct {

	// Name of node size
	Name string `json:"name,omitempty"`

	// Monthly cost per node in cents
	Cost int32 `json:"cost,omitempty"`

	// Disk quota (GB)
	DiskQuota int32 `json:"diskQuota,omitempty"`

	// Memory quota (MB)
	MemoryQuota int32 `json:"memoryQuota,omitempty"`

	// Number of CPU cores
	CpuCores int32 `json:"cpuCores,omitempty"`

	// Determines if the disk is backed by SSD
	SsdBacked bool `json:"ssdBacked,omitempty"`

	// Eligibility for free trial
	FreeTrialEligible bool `json:"freeTrialEligible,omitempty"`
}

// AssertNodeSizeRequired checks if the required fields are not zero-ed
func AssertNodeSizeRequired(obj NodeSize) error {
	return nil
}

// AssertNodeSizeConstraints checks if the values respects the defined constraints
func AssertNodeSizeConstraints(obj NodeSize) error {
	return nil
}
