/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

type RedisBundleOptionsSchema struct {

	// Accepts true/false. Enables Client ⇄ Node Encryption.
	ClientEncryption bool `json:"clientEncryption,omitempty"`

	// Accepts true/false. Enables Password Authentication and User Authorization.
	PasswordAuth bool `json:"passwordAuth,omitempty"`

	// The number of Redis Master Nodes to be created.
	MasterNodes int32 `json:"masterNodes,omitempty"`

	// The number of Redis Replica Nodes to be created.
	ReplicaNodes int32 `json:"replicaNodes,omitempty"`

	// Advertised HostName is required for PrivateLink.
	AdvertisedHostName string `json:"advertisedHostName,omitempty"`
}

// AssertRedisBundleOptionsSchemaRequired checks if the required fields are not zero-ed
func AssertRedisBundleOptionsSchemaRequired(obj RedisBundleOptionsSchema) error {
	return nil
}

// AssertRedisBundleOptionsSchemaConstraints checks if the values respects the defined constraints
func AssertRedisBundleOptionsSchemaConstraints(obj RedisBundleOptionsSchema) error {
	if obj.MasterNodes < 3 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.MasterNodes > 50 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	if obj.ReplicaNodes < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.ReplicaNodes > 50 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	return nil
}
