/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EncryptionKeyValidationResponseV2 struct {

	// Regions of the key
	Regions []AwsRegionV2 `json:"regions,omitempty"`

	// If the key is valid or invalid.
	IsValid bool `json:"isValid,omitempty"`

	// Detailed message of the validation result.
	Message string `json:"message,omitempty"`
}

// AssertEncryptionKeyValidationResponseV2Required checks if the required fields are not zero-ed
func AssertEncryptionKeyValidationResponseV2Required(obj EncryptionKeyValidationResponseV2) error {
	for _, el := range obj.Regions {
		if err := AssertAwsRegionV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEncryptionKeyValidationResponseV2Constraints checks if the values respects the defined constraints
func AssertEncryptionKeyValidationResponseV2Constraints(obj EncryptionKeyValidationResponseV2) error {
	return nil
}
