/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AwsSecurityGroupFirewallRulesV2 - A listable data source of all AWS Security Group based firewall rules in an Instaclustr managed cluster.
type AwsSecurityGroupFirewallRulesV2 struct {
	ClusterId string `json:"clusterId,omitempty"`

	FirewallRules []AwsSecurityGroupFirewallRuleV2 `json:"firewallRules,omitempty"`
}

// AssertAwsSecurityGroupFirewallRulesV2Required checks if the required fields are not zero-ed
func AssertAwsSecurityGroupFirewallRulesV2Required(obj AwsSecurityGroupFirewallRulesV2) error {
	for _, el := range obj.FirewallRules {
		if err := AssertAwsSecurityGroupFirewallRuleV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAwsSecurityGroupFirewallRulesV2Constraints checks if the values respects the defined constraints
func AssertAwsSecurityGroupFirewallRulesV2Constraints(obj AwsSecurityGroupFirewallRulesV2) error {
	return nil
}
