/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ProviderTagV2 struct {

	// Value of the tag to be added to the Data Centre.
	Value string `json:"value"`

	// Key of the tag to be added to the Data Centre.
	Key string `json:"key"`
}

// AssertProviderTagV2Required checks if the required fields are not zero-ed
func AssertProviderTagV2Required(obj ProviderTagV2) error {
	elements := map[string]interface{}{
		"value": obj.Value,
		"key":   obj.Key,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertProviderTagV2Constraints checks if the values respects the defined constraints
func AssertProviderTagV2Constraints(obj ProviderTagV2) error {
	return nil
}
