/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeleteClusterResponseSchema struct {
	Message string `json:"message,omitempty"`
}

// AssertDeleteClusterResponseSchemaRequired checks if the required fields are not zero-ed
func AssertDeleteClusterResponseSchemaRequired(obj DeleteClusterResponseSchema) error {
	return nil
}

// AssertDeleteClusterResponseSchemaConstraints checks if the values respects the defined constraints
func AssertDeleteClusterResponseSchemaConstraints(obj DeleteClusterResponseSchema) error {
	return nil
}
