/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PostgresqlReloadOperationsV2 - PostgreSQL reload operations
type PostgresqlReloadOperationsV2 struct {

	// List of reload operations
	ReloadOperations []PostgresqlReloadOperationV2 `json:"reloadOperations"`

	// ID of the PostgreSQL cluster
	ClusterId string `json:"clusterId"`
}

// AssertPostgresqlReloadOperationsV2Required checks if the required fields are not zero-ed
func AssertPostgresqlReloadOperationsV2Required(obj PostgresqlReloadOperationsV2) error {
	elements := map[string]interface{}{
		"reloadOperations": obj.ReloadOperations,
		"clusterId":        obj.ClusterId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.ReloadOperations {
		if err := AssertPostgresqlReloadOperationV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertPostgresqlReloadOperationsV2Constraints checks if the values respects the defined constraints
func AssertPostgresqlReloadOperationsV2Constraints(obj PostgresqlReloadOperationsV2) error {
	return nil
}
