/*
 * Instaclustr API Documentation
 *
 *
 *
 * API version: Current
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetSpecificMirrorResponse struct {

	// Id of the mirroring config.
	Id string `json:"id,omitempty"`

	// The overall status of this mirror
	Status string `json:"status,omitempty"`

	// The base name for the connectors of this mirror
	ConnectorName string `json:"connectorName,omitempty"`

	// The latency in milliseconds above which this mirror will be considered out of sync
	TargetLatency int32 `json:"targetLatency,omitempty"`

	// The original regular expression used to define which topics to mirror
	TopicsRegex string `json:"topicsRegex,omitempty"`

	// Status of the MirrorSourceConnector
	MirrorStatus string `json:"mirrorStatus,omitempty"`

	// Status of the CheckpointConnector
	CheckpointStatus string `json:"checkpointStatus,omitempty"`

	// List of mirrored topics, their average latencies and their average record rates
	TopicStatuses []TopicInfo `json:"topicStatuses,omitempty"`
}

// AssertGetSpecificMirrorResponseRequired checks if the required fields are not zero-ed
func AssertGetSpecificMirrorResponseRequired(obj GetSpecificMirrorResponse) error {
	for _, el := range obj.TopicStatuses {
		if err := AssertTopicInfoRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetSpecificMirrorResponseConstraints checks if the values respects the defined constraints
func AssertGetSpecificMirrorResponseConstraints(obj GetSpecificMirrorResponse) error {
	return nil
}
