# permissions for end users to view nodereloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodereload-viewer-role
rules:
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - nodereloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - nodereloads/status
  verbs:
  - get
