# permissions for end users to edit gcpvpcpeerings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcpvpcpeering-editor-role
rules:
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - gcpvpcpeerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - gcpvpcpeerings/status
  verbs:
  - get
