# permissions for end users to edit azurevnetpeerings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azurevnetpeering-editor-role
rules:
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - azurevnetpeerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - azurevnetpeerings/status
  verbs:
  - get
