# permissions for end users to view exclusionwindows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exclusionwindow-viewer-role
rules:
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - exclusionwindows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - exclusionwindows/status
  verbs:
  - get
