# permissions for end users to view gcpvpcpeerings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcpvpcpeering-viewer-role
rules:
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - gcpvpcpeerings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - gcpvpcpeerings/status
  verbs:
  - get
