# permissions for end users to view clusterbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterbackup-viewer-role
rules:
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - clusterbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - clusterbackups/status
  verbs:
  - get
