# permissions for end users to edit kafkaconnects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaconnect-editor-role
rules:
- apiGroups:
  - clusters.instaclustr.com
  resources:
  - kafkaconnects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.instaclustr.com
  resources:
  - kafkaconnects/status
  verbs:
  - get
