# permissions for end users to view awssecuritygroupfirewallrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awssecuritygroupfirewallrule-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: awssecuritygroupfirewallrule-viewer-role
rules:
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - awssecuritygroupfirewallrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - awssecuritygroupfirewallrules/status
  verbs:
  - get
