# permissions for end users to edit cassandrausers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cassandrauser-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: cassandrauser-editor-role
rules:
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - cassandrausers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterresources.instaclustr.com
  resources:
  - cassandrausers/status
  verbs:
  - get
