# permissions for end users to edit mirrors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirror-editor-role
rules:
- apiGroups:
  - kafkamanagement.instaclustr.com
  resources:
  - mirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafkamanagement.instaclustr.com
  resources:
  - mirrors/status
  verbs:
  - get
