# permissions for end users to edit kafkaacls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kafkaacl-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: kafkaacl-editor-role
rules:
- apiGroups:
  - kafkamanagement.instaclustr.com
  resources:
  - kafkaacls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafkamanagement.instaclustr.com
  resources:
  - kafkaacls/status
  verbs:
  - get
