# permissions for end users to view mirrors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirror-viewer-role
rules:
- apiGroups:
  - kafkamanagement.instaclustr.com
  resources:
  - mirrors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kafkamanagement.instaclustr.com
  resources:
  - mirrors/status
  verbs:
  - get
