---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - clusters.instaclustr.com
  resources:
  - cassandras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.instaclustr.com
  resources:
  - cassandras/finalizers
  verbs:
  - update
- apiGroups:
  - clusters.instaclustr.com
  resources:
  - cassandras/status
  verbs:
  - get
  - patch
  - update
