apiVersion: clusters.instaclustr.com/v1beta1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: redis-sample-restored
spec:
  restoreFrom:
    clusterId: "1bece950-c79d-441b-8363-6b8cd9069db0"
    restoredClusterName: "redisRESTORED"
    pointInTime: 1677505625158