apiVersion: clusterresources.instaclustr.com/v1beta1
kind: OpenSearchEgressRules
metadata:
  labels:
    app.kubernetes.io/name: opensearchegressrules
    app.kubernetes.io/instance: opensearchegressrules-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: opensearchegressrules-sample
spec:
#  clusterId: "5425d1ed-7a6b-44da-965e-6f085e85b6d0"
  clusterRef:
    name: opensearch-sample
    namespace: default
    clusterKind: OpenSearch
  openSearchBindingId: "rJLtJYwBbvQX8Rgdz9SR"
  source: "NOTIFICATIONS"
  type: "SLACK"
