apiVersion: clusters.instaclustr.com/v1alpha1
kind: Cadence
metadata:
  labels:
    app.kubernetes.io/name: cadence
    app.kubernetes.io/instance: cadence-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: cadence-sample
spec:
  name: "operatorCadence"
  version: "cadence:0.24.0"
#  concurrentResizes: 1
#  notifySupportContacts: false
  dataCentres:
  - region: "US_EAST_1"
    network: "10.1.0.0/16"
    cloudProvider: "AWS_VPC"
    nodeSize: "CAD-SI-DEV-t3.small-5"
    racksNumber: 2
    nodesNumber: 1
    cadenceNodeCount: 1
    provisioningType: "SHARED"
    targetCassandraVpcType: "TARGET_VPC"
    targetCassandraCdcId: "f2a61989-7df9-475e-87c6-26f5b6775519"
    #  twoFactorDelete:
    #    - email: "rostyslp@netapp.com"
    #  description: "test 222"
  slaTier: "NON_PRODUCTION"
