apiVersion: clusters.instaclustr.com/v1beta1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: redis-sample
spec:
  name: "testRedis"
  version: "7.0.9"
  slaTier: "NON_PRODUCTION"
  clientEncryption: false
  passwordAndUserAuth: false
  #  twoFactorDelete:
  #    - email: "rostyslp@netapp.com"
  dataCentres:
    - region: "US_WEST_2"
      cloudProvider: "AWS_VPC"
      network: "10.1.0.0/16"
      #      nodeSize: "t3.medium-80-r"
      nodeSize: "t3.small-20-r"
      masterNodes: 3
      nodesNumber: 0
#    - region: "US_WEST_2"
#      name: "testDC2"
#      cloudProvider: "AWS_VPC"
#      network: "10.2.0.0/16"
#      nodeSize: "t3.small-20-r"
#      nodesNumber: 0
#      masterNodes: 3