#apiVersion: v1
#kind: Secret
#metadata:
#  name: inst-test-aws-cred-secret
#data:
#  awsAccessKeyId: access_key
#  awsSecretAccessKey: secret_key
#---
apiVersion: clusters.instaclustr.com/v1beta1
kind: Cadence
metadata:
  name: cadence-sample
spec:
  name: "operatorCadence"
  version: "0.24.0"
  standardProvisioning:
    - targetCassandra:
        dependencyCdcId: "9d43ac54-7317-4ce5-859a-e9d0443508a4"
        dependencyVpcType: "VPC_PEERED"
  #  packagedProvisioning:
  #    - bundledCassandraSpec:
  #        nodeSize: "CAS-DEV-t4g.small-5"
  #        network: "10.2.0.0/16"
  #        replicationFactor: 3
  #        nodesNumber: 3
  #        privateIPBroadcastForDiscovery: false
  #        passwordAndUserAuth: true
  #      useAdvancedVisibility: true
  #      bundledKafkaSpec:
  #        nodeSize: "KFK-DEV-t4g.small-5"
  #        nodesNumber: 3
  #        network: "10.3.0.0/16"
  #        replicationFactor: 3
  #        partitionsNumber: 3
  #      bundledOpenSearchSpec:
  #        nodeSize: "SRH-DEV-t4g.small-5"
  #        replicationFactor: 3
  #        nodesPerReplicationFactor: 1
  #        network: "10.4.0.0/16"
  #  twoFactorDelete:
  #  - email: "rostyslp@netapp.com"
  privateNetworkCluster: false
  dataCentres:
    - region: "US_EAST_1"
      network: "10.12.0.0/16"
      cloudProvider: "AWS_VPC"
      name: "testdc"
      nodeSize: "CAD-DEV-t3.small-5"
      nodesNumber: 2
      clientEncryption: false
  slaTier: "NON_PRODUCTION"
  useCadenceWebAuth: true

