#apiVersion: v1
#kind: Secret
#metadata:
#  name: inst-test-aws-cred-secret
#data:
#  awsAccessKeyId: access_key
#  awsSecretAccessKey: secret_key
#---
apiVersion: clusters.instaclustr.com/v1alpha1
kind: Cadence
metadata:
  labels:
    app.kubernetes.io/name: cadence
    app.kubernetes.io/instance: cadence-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: cadence-sample2
  annotations:
    test.annotation/first: testAnnotation
#    test.annotation/second: testAnnotation
spec:
  name: "operatorCadence"
  version: "cadence:0.24.0"
  concurrentResizes: 1
  notifySupportContacts: false
  dataCentres:
  - region: "US_EAST_1"
    network: "10.3.0.0/16"
    cloudProvider: "AWS_VPC"
#    nodeSize: "CAD-SI-DEV-t3.small-5"
#    nodeSize: "CAD-DEV-t3.medium-30"
    nodeSize: "CAD-DEV-t3.small-5"
    racksNumber: 3
    nodesNumber: 1
    cadenceNodeCount: 2
#    targetCassandraVpcType: "TARGET_VPC"
#    targetCassandraCdcId: "424a1e29-a288-4b7c-863e-00ff231fd3f0"
    #  twoFactorDelete:
    #    - email: "rostyslp@netapp.com"
  description: "test 222"
  slaTier: "NON_PRODUCTION"
  provisioningType: "PACKAGED"
#  provisioningType: "SHARED"
#  provisioningType: "STANDARD"
#  enableArchival: true
#  archivalS3Uri: "s3://k8s-operator-insta-test/cadence-archival-test"
#  archivalS3Region: "us-east-1"
#  awsAccessKeySecretName: "inst-test-aws-cred-secret"
#  awsAccessKeySecretNamespace: "default"
  cassandraNodeSize: "CAS-DEV-t4g.small-5"
  cassandraNetwork: "10.1.0.0/16"
  cassandraReplicationFactor: 3
  cassandraNodesNumber: 3
  cassandraPrivateIPBroadcastForDiscovery: false
  cassandraPasswordAndUserAuth: true
  useAdvancedVisibility: true
  kafkaNodeSize: "KFK-DEV-t4g.small-5"
  kafkaNodesNumber: 3
  kafkaNetwork: "10.2.0.0/16"
  kafkaReplicationFactor: 3
  kafkaPartitionsNumber: 3
  opensearchNodeSize: "SRH-DEV-t4g.small-5"
  opensearchReplicationFactor: 3
  openSearchNodesPerReplicationFactor: 1
  openSearchNetwork: "10.4.0.0/16"
