apiVersion: clusters.instaclustr.com/v1alpha1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: redis-sample
spec:
  restoreFrom:
    clusterId: "3e5f1e73-5f6e-4b72-a78b-73f194735471"
    clusterNameOverride: "redisRESTORED"
    pointInTime: 1676370398898
    clusterNetwork: "10.13.0.0/16"