apiVersion: clusterresources.instaclustr.com/v1beta1
kind: AWSVPCPeering
metadata:
  labels:
    app.kubernetes.io/name: awsvpcpeering
    app.kubernetes.io/instance: awsvpcpeering-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: awsvpcpeering-sample
spec:
  peerAwsAccountId: "152668027680"
  peerSubnets:
    - "172.31.0.0/16"
    - "192.168.0.0/16"
  peerVpcId: "vpc-87241ae1"
  peerRegion: "US_EAST_1"
#  cdcId: b815c694-2f99-4b69-a315-19b958cbb52c
  clusterRef:
    name: kafka
    namespace: default
    clusterKind: Kafka