apiVersion: clusters.instaclustr.com/v1beta1
kind: KafkaConnect
metadata:
  name: kafkaconnect-sample
spec:
  dataCentres:
    - name: "US_EAST_1_DC_KAFKA"
      nodesNumber: 3
#      nodesNumber: 6
      cloudProvider: "AWS_VPC"
      replicationFactor: 3
      tags:
        tag: "oneTag"
        tag2: "twoTags"
      nodeSize: "KCN-DEV-t4g.medium-30"
      network: "10.15.0.0/16"
      region: "US_EAST_1"
  clusterResources:
    clusterNetworkFirewallRules:
              - namespace: default
                name: clusternetworkfirewallrule-sample
    awsVPCPeerings:
#              - namespace: default
#                name: awsvpcpeering-sample
    awsSecurityGroupFirewallRules:
#              - namespace: default
#                name: awssecuritygroupfirewallrule-sample
    exclusionWindows:
#              - namespace: default
#                name: exclusionwindow-sample
    gcpVPCPeerings:
    #      - namespace: default
    #        name: gcpvpcpeering-sample
    #      - namespace: default
    #        name: gcpvpcpeering-sample-two
    azureVNetPeerings:
    #      - namespace: default
    #        name: azurevnetpeering-sample
    #      - namespace: default
    #        name: azurevnetpeering-sample-trough
  name: "oleksandr-KC"
  version: "3.5.1"
  privateNetworkCluster: false
  slaTier: "NON_PRODUCTION"
  targetCluster:
    - managedCluster:
        - targetKafkaClusterId: "34dfc53c-c8c1-4be8-bd2f-cfdb77ec7349"
          kafkaConnectVpcType: "KAFKA_VPC"
