apiVersion: clusters.instaclustr.com/v1beta1
kind: KafkaConnect
metadata:
  name: kafkaconnect-sample
spec:
  name: "example-KC"
  dataCentres:
    - name: "US_EAST_1_DC_KAFKA"
      nodesNumber: 3
      cloudProvider: "AWS_VPC"
      replicationFactor: 3
      tags:
        tag: "oneTag"
        tag2: "twoTags"
      nodeSize: "KCN-DEV-t4g.medium-30"
      network: "10.32.0.0/16"
      region: "US_EAST_1"
  version: "3.5.1"
  privateNetwork: false
  slaTier: "NON_PRODUCTION"
  targetCluster:
    - managedCluster:
#        - targetKafkaClusterId: 9b5ba158-12f5-4681-a279-df5c371b417c
        - clusterRef:
            name: kafka
            namespace: default
            clusterKind: Kafka
          kafkaConnectVpcType: "KAFKA_VPC"
