apiVersion: clusters.instaclustr.com/v1beta1
kind: OpenSearch
metadata:
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: opensearch-sample
  annotations:
    test.annotation/first: testAnnotation
spec:
  name: opensearch-test
  alertingPlugin: false
  anomalyDetectionPlugin: false
  asynchronousSearchPlugin: false
#  userRefs:
#    - name: "test-user-1"
#      namespace: "default"
#    - name: "test-user-2"
#      namespace: "default"
  clusterManagerNodes:
  - dedicatedManager: false
    nodeSize: SRH-DEV-t4g.small-5
  dataCentres:
    - cloudProvider: AWS_VPC
      name: AWS_VPC_US_EAST_1
      network: 10.0.0.0/16
      numberOfRacks: 3
      privateLink: false
      region: US_EAST_1
#      awsSettings:
#        - backupBucket: instaclustr-us-east-1-backups-preprod
#  ingestNodes:
##   - nodeSize: SRH-DI-PRD-m6g.large-10
#    - nodeSize: SRH-DI-DEV-t4g.small-5
#      nodeCount: 3
#  dataNodes:
#    - nodesNumber: 3
#      nodeSize: SRH-DEV-t4g.small-5
  icuPlugin: false
  indexManagementPlugin: true
  knnPlugin: false
  loadBalancer: false
  notificationsPlugin: false
#  opensearchDashboards:
#    - nodeSize: SRH-DEV-t4g.small-5
#      oidcProvider: ''
#      version: opensearch-dashboards:2.5.0
  version: 2.11.1
  pciCompliance: false
  privateNetwork: false
  reportingPlugin: false
  slaTier: NON_PRODUCTION
  sqlPlugin: false
#  resizeSettings:
#    - notifySupportContacts: false
#      concurrency: 3