apiVersion: clusterresources.instaclustr.com/v1alpha1
kind: ClusterNetworkFirewallRule
metadata:
  labels:
    app.kubernetes.io/name: clusternetworkfirewallrule
    app.kubernetes.io/instance: clusternetworkfirewallrule-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: clusternetworkfirewallrule-sample
spec:
  # TODO(user): Add fields here
