apiVersion: clusters.instaclustr.com/v1alpha1
kind: Kafka
metadata:
  name: kafka
spec:
  name: "kafkaOperator"
  version: "2.7.1"
  pciCompliance: false
  replicationFactorNumber: 3
  partitionsNumber: 3
  allowDeleteTopics: true
  autoCreateTopics: true
  clientToClusterEncryption: true
  slaTier: "NON_PRODUCTION"
  dataCentres:
    - name: "US_EAST_1_DC_KAFKA"
      nodesNumber: 3
      cloudProvider: "AWS_VPC"
      tags:
        tag: "oneTag"
        tag2: "twoTags"
      nodeSize: "KFK-DEV-t4g.small-5"
      network: "192.168.0.0/18"
      region: "US_EAST_1"
  dedicatedZookeeper:
    - nodeSize: "KDZ-DEV-t4g.small-30"
      nodesNumber: 3
  privateNetworkCluster: true
