apiVersion: clusters.instaclustr.com/v1alpha1
kind: KafkaConnect
metadata:
  name: kafkaconnect-sample
spec:
  dataCentres:
    - name: "US_EAST_1_DC_KAFKA"
      nodesNumber: 9
      cloudProvider: "AWS_VPC"
      replicationFactor: 3
      tags:
        tag: "oneTag"
        tag2: "twoTags"
      nodeSize: "KCN-DEV-t4g.medium-30"
      network: "10.15.0.0/16"
      region: "US_EAST_1"
  name: "kafkaConnectOperator"
  version: "3.1.2"
  privateNetworkCluster: false
  slaTier: "NON_PRODUCTION"
  targetCluster:
    - managedCluster:
        - targetKafkaClusterId: "a80949dd-e8e9-43a5-b0a0-47d74f3eae3f"
          kafkaConnectVpcType: "KAFKA_VPC"
