apiVersion: clusterresources.instaclustr.com/v1beta1
kind: ClusterNetworkFirewallRule
metadata:
  labels:
    app.kubernetes.io/name: clusternetworkfirewallrule
    app.kubernetes.io/instance: clusternetworkfirewallrule-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: clusternetworkfirewallrule-sample
spec:
  network: 54.198.214.167/32
#  clusterId: c47c6a1c-9e2b-4a5c-aa5e-7013bceecd09
  type: POSTGRESQL
