apiVersion: clusters.instaclustr.com/v1alpha1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: redis-sample
spec:
  name: "testRedis"
  version: "redis:7.0.5"
  slaTier: "NON_PRODUCTION"
  concurrentResizes: 1
  notifySupportContacts: false
  dataCentres:
    - region: "US_WEST_2"
      cloudProvider: "AWS_VPC"
      network: "10.1.0.0/16"
      nodeSize: "t3.medium-80-r"
#      nodeSize: "t3.small-20-r"
      nodesNumber: 3
      racksNumber: 3
      masterNodes: 3
      replicaNodes: 3
    - region: "US_WEST_2"
      name: "test"
      cloudProvider: "AWS_VPC"
      network: "10.2.0.0/16"
      nodeSize: "t3.small-20-r"
      nodesNumber: 3
      racksNumber: 3
      masterNodes: 3
      replicaNodes: 3