apiVersion: clusters.instaclustr.com/v1alpha1
kind: Cassandra
metadata:
  name: cassandra-cluster
spec:
  name: "Username-Cassandra"
  version: "4.0.10"
  dataCentres:
    - name: "AWS_cassandra"
      region: "US_EAST_1"
      cloudProvider: "AWS_VPC"
      continuousBackup: false
      nodesNumber: 2
      replicationFactor: 2
      privateIpBroadcastForDiscovery: false
      network: "172.16.0.0/19"
      tags:
        "tag": "testTag"
      clientToClusterEncryption: false
      nodeSize: "CAS-DEV-t4g.small-5"
#    - name: "AWS_cassandra2"
#      region: "US_EAST_1"
#      cloudProvider: "AWS_VPC"
#      continuousBackup: false
#      nodesNumber: 2
#      replicationFactor: 2
#      privateIpBroadcastForDiscovery: false
#      network: "172.17.0.0/19"
#      tags:
#        "tag": "testTag"
#      clientToClusterEncryption: false
#      nodeSize: "CAS-DEV-t4g.small-30"
  pciCompliance: false
  luceneEnabled: false        # can be enabled only on 3.11.13 version of Cassandra
  passwordAndUserAuth: true
#  userRef:
#    namespace: default
#    name: cassandrauser-sample
  slaTier: "NON_PRODUCTION"
#  twoFactorDelete:
#    - email: "rostyslp@netapp.com"
  #spark:
   # - version: "2.3.2"         # 3.0.1 for 4.0.4 version of Cassandra | 2.3.2 for 3.11.13 version of Cassandra

