apiVersion: clusterresources.instaclustr.com/v1beta1
kind: ExclusionWindow
metadata:
  name: exclusionwindow-sample
spec:
#  clusterId: "d72b0c01-d263-40c7-8d3d-adb837602647"
  dayOfWeek: "MONDAY"
  startHour: 10
  durationInHours: 40
