apiVersion: clusters.instaclustr.com/v1alpha1
kind: OpenSearch
metadata:
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: opensearch-sample
  annotations:
    test.annotation/first: testAnnotation
spec:
  restoreFrom:
    clusterId: "8c20c38d-c557-4664-af53-549ce0e3914f"
    pointInTime: 1675684224808
    clusterNameOverride: "opensearchRESTORED"
