apiVersion: clusterresources.instaclustr.com/v1beta1
kind: NodeReload
metadata:
  name: nodereload-sample
spec:
  nodes:
    - nodeID: "8b5e3cb1-d1ca-400c-92e5-3279a79133a2"
    - nodeID: "8de5f5ad-d776-4c19-a322-1efffe149018"
