apiVersion: clusters.instaclustr.com/v1beta1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: redis-sample
spec:
  name: "Username-redis"
  version: "7.0.14"
  slaTier: "NON_PRODUCTION"
  clientEncryption: false
  passwordAndUserAuth: true
  privateNetworkCluster: false
  userRefs:
#      - name: redisuser-sample-1
#        namespace: default
#      - name: redisuser-sample-2
#        namespace: default
#      - name: redisuser-sample-3
#        namespace: default
  #  twoFactorDelete:
  #    - email: "rostyslp@netapp.com"
  dataCentres:
    - region: "US_WEST_2"
      name: "testDC1"
      cloudProvider: "AWS_VPC"
      network: "10.1.0.0/16"
#      nodeSize: "r6g.large-100-r"
#      nodeSize: "RDS-DEV-t4g.medium-80"
      nodeSize: "RDS-DEV-t4g.small-20"
      masterNodes: 3
      nodesNumber: 0
      replicationFactor: 0
#      tags:
#        tag: "oneTag"
#        tag2: "twoTags"
#      privateLink:
#        - advertisedHostname: redis-sample-test.com
#    - region: "US_WEST_2"
#      name: "testDC2"
#      cloudProvider: "AWS_VPC"
#      network: "10.2.0.0/16"
#      nodeSize: "RDS-DEV-t4g.small-20"
#      nodesNumber: 0
#      masterNodes: 3
#      replicationFactor: 0
#  resizeSettings:
#    - notifySupportContacts: false
#      concurrency: 1