apiVersion: clusterresources.instaclustr.com/v1beta1
kind: ClusterNetworkFirewallRule
metadata:
  labels:
    app.kubernetes.io/name: clusternetworkfirewallrule
    app.kubernetes.io/instance: clusternetworkfirewallrule-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: clusternetworkfirewallrule-sample
spec:
  network: 62.212.64.19/32
#  clusterId: 59ff1cc6-9b1c-4755-85e3-9ef4d892a96e
  type: KAFKA_CONNECT
  clusterRef:
    name: kafkaconnect-sample
    namespace: default
    clusterKind: KafkaConnect
