apiVersion: v1
kind: Secret
metadata:
  name: redis-user-test-1
data:
  username: bXlreXRhCg== #mykyta
  password: VGVzdDEyMyEK #Test123!
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-user-test-2
data:
  username: c3Rhcwo= #stas
  password: VGVzdDEyMyEh #Test123!!
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-user-test-3
data:
  username: Ym9oZGFuCg== #bohdan
  password: VGVzdDEyMzQ1IQo= #Test12345!
---
apiVersion: clusterresources.instaclustr.com/v1beta1
kind: RedisUser
metadata:
  name: redisuser-sample-1
spec:
  initialPermissions: "none"
  secretRef:
    name: "redis-user-test-1" #metadata name
    namespace: "default"
---
apiVersion: clusterresources.instaclustr.com/v1beta1
kind: RedisUser
metadata:
  name: redisuser-sample-2
spec:
  initialPermissions: "none"
  secretRef:
    name: "redis-user-test-2" #metadata name
    namespace: "default"
---
apiVersion: clusterresources.instaclustr.com/v1beta1
kind: RedisUser
metadata:
  name: redisuser-sample-3
spec:
  initialPermissions: "none"
  secretRef:
    name: "redis-user-test-3" #metadata name
    namespace: "default"