apiVersion: clusters.instaclustr.com/v1alpha1
kind: OpenSearch
metadata:
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: opensearch-sample
spec:
  name: "testOpensearch"
  version: "opensearch:2.2.1"
  concurrentResizes: 1
  notifySupportContacts: false
  dataCentres:
    - region: "US_WEST_2"
      network: "10.1.0.0/16"
      cloudProvider: "AWS_VPC"
      nodeSize: "SRH-DEV-t4g.medium-30"
      racksNumber: 3
      nodesNumber: 1
      indexManagementPlugin: true
  #  clusterConfigurations:
  #    idle_in_transaction_session_timeout: "3"
  #  twoFactorDelete:
  #    - email: "rostyslp@netapp.com"
  #  description: "test 222"
  slaTier: "NON_PRODUCTION"