apiVersion: clusters.instaclustr.com/v1beta1
kind: Cassandra
metadata:
  name: cassandra-on-prem-cluster
spec:
  name: "danylo-on-prem-cassandra"
  version: "4.0.10"
  privateNetworkCluster: true
  onPremisesSpec:
    storageClassName: managed-csi-premium
    osDiskSize: 20Gi
    dataDiskSize: 200Gi
    sshGatewayCPU: 2
    sshGatewayMemory: 4096Mi
    nodeCPU: 2
    nodeMemory: 8192Mi
    osImageURL: "https://s3.amazonaws.com/debian-bucket/debian-11-generic-amd64-20230601-1398.raw"
    cloudInitScriptNamespacedName:
      namespace: default
      name: instaclustr-cloud-init-secret
    cniType: "Calico"
    staticIPs:
      sshGateway: "192.168.150.1"
      nodes:
        - "192.168.150.2"
        - "192.168.150.3"
        - "192.168.150.4"
  dataCentres:
    - name: "onPremCassandra"
      region: "CLIENT_DC"
      cloudProvider: "ONPREMISES"
      continuousBackup: false
      nodesNumber: 3
      replicationFactor: 3
      privateIpBroadcastForDiscovery: true
      network: "192.168.0.0/16"
      tags:
        "onprem": "test"
      clientToClusterEncryption: false
      nodeSize: "CAS-PRD-OP.4.8-200"
  pciCompliance: false
  luceneEnabled: false        # can be enabled only on 3.11.13 version of Cassandra
  passwordAndUserAuth: false
  slaTier: "NON_PRODUCTION"
