apiVersion: clusterresources.instaclustr.com/v1beta1
kind: MaintenanceEvents
metadata:
  name: maintenanceevents-sample
spec:
  maintenanceEventsReschedule:
    - scheduledStartTime: "2023-11-09T02:30:00Z"
      maintenanceEventId: "d9199351-8438-4da9-8828-ab7a0dde640e"
