apiVersion: clusterresources.instaclustr.com/v1beta1
kind: GCPVPCPeering
metadata:
  name: gcpvpcpeering-sample
spec:
  cdcId: 095f8410-ee09-473a-afcd-69c74271a750
  clusterRef:
    name: redis-sample
    namespace: default
    clusterKind: Redis
  peerProjectId: netapp-hcl-seclab
  peerSubnets:
    - 192.168.0.0/16
    - 172.16.0.0/16
  peerVpcNetworkName: hcl-seclab-client-vpc1
