apiVersion: clusterresources.instaclustr.com/v1alpha1
kind: GCPVPCPeering
metadata:
  name: gcpvpcpeering-sample
spec:
  cdcId: f3eab841-6952-430d-ba90-1bfc3f15da10
  peerProjectId: example-project123
  peerSubnets:
    - 10.1.0.0/16
  peerVpcNetworkName: network-aabb1122
