apiVersion: clusterresources.instaclustr.com/v1beta1
kind: MaintenanceEvents
metadata:
  name: maintenanceevents-sample
spec:
  maintenanceEventsReschedule:
    - scheduledStartTime: "2023-11-09T04:30:00Z"
      maintenanceEventId: "0d25b466-bc22-44a8-b15d-8f92e815cb6e"
    - scheduledStartTime: "2023-11-15T06:00:00Z"
      maintenanceEventId: "d4806381-cd1e-48df-b9ba-70f9b0829c72"
