apiVersion: clusters.instaclustr.com/v1alpha1
kind: PostgreSQL
metadata:
  name: postgresql-sample
spec:
  clusterName: "testPostgreSQL"
  provider:
    name: "AWS_VPC"
  nodeSize: "PGS-DEV-t4g.small-5"
  dataCentre: "US_WEST_2"
  bundles:
    - bundle: "POSTGRESQL"
      version: "14.5"
      options:
        postgresqlNodeCount: 2
