apiVersion: clusters.instaclustr.com/v1beta1
kind: Cassandra
metadata:
  name: cassandra-cluster
spec:
  name: "username-Cassandra"
  version: "4.0.10"
  privateNetworkCluster: false
  dataCentres:
    - name: "AWS_cassandra"
      region: "US_EAST_1"
      debezium:
        - kafkaVpcType: "VPC_PEERED"
          kafkaTopicPrefix: "test"
          kafkaCdcId: "5134aed3-7b98-4ebd-95d0-2e181bdb073b"
          version: "2.0.1"
      cloudProvider: "AWS_VPC"
      continuousBackup: false
      nodesNumber: 2
      replicationFactor: 2
      privateIpBroadcastForDiscovery: false
      network: "172.16.0.0/19"
      tags:
        "tag": "testTag"
      clientToClusterEncryption: false
      # cloudProviderSettings:
      #   - customVirtualNetworkId: "vpc-0b69c781969e980a9"
      nodeSize: "CAS-DEV-t4g.small-5"
      # accountName: "InstaclustrRIYOA"
  #    - name: "AWS_cassandra2"
  #      region: "US_EAST_1"
  #      cloudProvider: "AWS_VPC"
  #      continuousBackup: false
  #      nodesNumber: 2
  #      replicationFactor: 2
  #      privateIpBroadcastForDiscovery: false
  #      network: "172.17.0.0/19"
  #      tags:
  #        "tag": "testTag"
  #      clientToClusterEncryption: false
  #      nodeSize: "CAS-DEV-t4g.small-30"
  pciCompliance: false
  luceneEnabled: false        # can be enabled only on 3.11.13 version of Cassandra
  passwordAndUserAuth: true
  #  userRefs:
  #    - namespace: default
  #      name: cassandrauser-sample
  #    - namespace: default
  #      name: cassandrauser-sample2
  #    - namespace: default
  #      name: cassandrauser-sample3
  slaTier: "NON_PRODUCTION"
    #  resizeSettings:
    #    - notifySupportContacts: false
    #      concurrency: 2
    #  description: "this is a sample of description"
    #  twoFactorDelete:
    #    - email: "rostyslp@netapp.com"
  #spark:
  # - version: "2.3.2"         # 3.0.1 for 4.0.4 version of Cassandra | 2.3.2 for 3.11.13 version of Cassandra