#apiVersion: v1
#kind: Secret
#metadata:
#  name: inst-test-aws-cred-secret
#data:
#  awsAccessKeyId: access_key
#  awsSecretAccessKey: secret_key
#---
apiVersion: clusters.instaclustr.com/v1beta1
kind: Cadence
metadata:
  name: cadence-sample
spec:
  name: "bohdan-cadence-test"
  version: "1.2.2"
#  standardProvisioning:
#    - targetCassandra:
#        dependencyCdcId: "9d43ac54-7317-4ce5-859a-e9d0443508a4"
#        dependencyVpcType: "VPC_PEERED"
  packagedProvisioning:
    - useAdvancedVisibility: true
      solutionSize: "Production-Small"
  #  twoFactorDelete:
  #  - email: "rostyslp@netapp.com"
  privateNetwork: false
  dataCentres:
    - region: "US_EAST_1"
      network: "10.251.0.0/16"
      # In a multi-region mode setup, ensure the CIDR block for the secondary cluster does not overlap with the primary one
#      network: "10.16.0.0/16"
      cloudProvider: "AWS_VPC"
      name: "testdc"
#      nodeSize: "CAD-PRD-m5ad.large-75"
      nodeSize: "CAD-DEV-t3.small-5"
      nodesNumber: 2
      clientEncryption: false
#      privateLink:
#        - advertisedHostname: "cadence-sample-test.com"
  slaTier: "NON_PRODUCTION"
  useCadenceWebAuth: false
  useHttpApi: false
  #  targetPrimaryCadence:
#    - dependencyCdcId: "cce79be3-7f41-4cad-837c-86d3d8b4be77"
#      dependencyVpcType: "SEPARATE_VPC"
  resizeSettings:
    - notifySupportContacts: false
      concurrency: 1