apiVersion: v1
kind: Secret
metadata:
  name: cassandra-user-secret
data:
  password: NDgxMzU5ODM1NzlmMDU0ZTlhY2I4ZjcxMTMzMzQ1MjM3ZQ==
  username: b2xvbG8=
---

apiVersion: clusterresources.instaclustr.com/v1beta1
kind: CassandraUser
metadata:
  name: cassandrauser-sample
spec:
  secretRef:
    name: "cassandra-user-secret"
    namespace: "default"
