apiVersion: clusters.instaclustr.com/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper-sample
spec:
  dataCentres:
    - clientToServerEncryption: false
      cloudProvider: "AWS_VPC"
      name: "MyTestDataCentre1"
      network: "10.0.0.0/16"
#      nodeSize: "zookeeper-developer-t3.small-20"
      nodeSize: "zookeeper-production-m5.large-60"
      nodesNumber: 3
      region: "US_EAST_1"
  name: "Username-zookeeper"
  privateNetworkCluster: false
  slaTier: "NON_PRODUCTION"
  version: "3.8.2"
