apiVersion: clusters.instaclustr.com/v1beta1
kind: Cassandra
metadata:
  name: cassandra-cluster
spec:
  name: "username-cassandra" #(immutable)
  version: "4.1.13" #(immutable)
  privateNetwork: false #(immutable)
  dataCentres:
    - name: "AWS_cassandra" #(mutable)
      region: "US_EAST_1" #(immutable)
#      debezium:
#        - kafkaVpcType: "VPC_PEERED" #(immutable)
#          kafkaTopicPrefix: "test" #(immutable)
#          kafkaCdcId: 8db44d06-3cd6-4bb3-86fb-c9b1e2a03941 #(mutable)
#          clusterRef:
#            name: kafka
#            namespace: default
#            clusterKind: Kafka
#          version: "2.0.1" #(immutable)
      cloudProvider: "AWS_VPC" #(immutable)
      continuousBackup: false #(immutable)
      nodesNumber: 2 #(mutable)
      replicationFactor: 2
      privateIpBroadcastForDiscovery: false #(immutable)
      network: "172.16.0.0/19" #(immutable)
      tags:
        "tag": "testTag" #(immutable)
      clientToClusterEncryption: true #(immutable)
#      cloudProviderSettings:
#        - customVirtualNetworkId: "vpc-0b69c781969e980a9"
      nodeSize: "CAS-DEV-t4g.small-5" #(mutable)
#      nodeSize: "CAS-PRD-r6g.medium-80" #(mutable) # (production node size)
#      nodeSize: "CAS-PRD-r6g.medium-120" #(mutable) # (production node size)
      privateLink: false
#      shotoverProxy:
#        - nodeSize: "CSO-PRD-c6g.xlarge-20"
  #      accountName: "InstaclustrRIYOA"
#    - name: "AWS_cassandra2"
#      region: "US_EAST_1"
#      cloudProvider: "AWS_VPC"
#      continuousBackup: false
#      nodesNumber: 2
#      replicationFactor: 2
#      privateIpBroadcastForDiscovery: false
#      network: "172.17.0.0/19"
#      tags:
#        "tag": "testTag"
#      clientToClusterEncryption: false
#      nodeSize: "CAS-DEV-t4g.small-30"
  pciCompliance: false #(immutable)
  luceneEnabled: false   #(immutable)     # can be enabled only on 3.11.13 version of Cassandra (currently it could be enabled on 4.0.10 version as well)
  passwordAndUserAuth: true #(immutable)
#  userRefs:
#    - namespace: default
#      name: cassandrauser-sample
  #    - namespace: default
  #      name: cassandrauser-sample2
  #    - namespace: default
  #      name: cassandrauser-sample3
  slaTier: "NON_PRODUCTION" #(immutable)
    #  resizeSettings:
    #    - notifySupportContacts: false
    #      concurrency: 2
    #  description: "this is a sample of description"
    #  twoFactorDelete:
    #    - email: "rostyslp@netapp.com"