apiVersion: clusterresources.instaclustr.com/v1alpha1
kind: GCPVPCPeering
metadata:
  name: gcpvpcpeering-sample
spec:
  cdcId: ac3e6fea-da06-42cf-9b08-b3b29f518331
  peerProjectId: netapp-hcl-seclab
  peerSubnets:
    - 192.168.0.0/16
    - 172.16.0.0/16
  peerVpcNetworkName: hcl-seclab-client-vpc1
