apiVersion: clusters.instaclustr.com/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper-sample
spec:
  dataCentres:
    - clientToServerEncryption: false
      cloudProvider: "AWS_VPC"
      name: "MyTestDataCentre1"
      network: "10.0.0.0/16"
#      nodeSize: "zookeeper-developer-t3.small-20"
      nodeSize: "zookeeper-production-m5.large-60"
      nodesNumber: 3
      region: "US_EAST_1"
  clusterResources:
    clusterNetworkFirewallRules:
#      - namespace: default
#        name: clusternetworkfirewallrule-sample
    awsVPCPeerings:
      - namespace: default
        name: awsvpcpeering-sample
    awsSecurityGroupFirewallRules:
#      - namespace: default
#        name: awssecuritygroupfirewallrule-sample
    exclusionWindows:
#      - namespace: default
#        name: exclusionwindow-sample
    gcpVPCPeerings:
    #      - namespace: default
    #        name: gcpvpcpeering-sample
    #      - namespace: default
    #        name: gcpvpcpeering-sample-two
    azureVNetPeerings:
    #      - namespace: default
    #        name: azurevnetpeering-sample
    #      - namespace: default
    #        name: azurevnetpeering-sample-trough
  name: "Username-zookeeper"
  privateNetworkCluster: false
  slaTier: "NON_PRODUCTION"
  version: "3.8.2"
