apiVersion: clusterresources.instaclustr.com/v1alpha1
kind: ClusterNetworkFirewallRule
metadata:
  labels:
    app.kubernetes.io/name: clusternetworkfirewallrule
    app.kubernetes.io/instance: clusternetworkfirewallrule-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: clusternetworkfirewallrule-sample
spec:
  network: 62.212.64.19/32
  clusterId: bb7166e4-cffa-48e7-8f0a-5ee32873b750
  type: CASSANDRA_CQL
