apiVersion: v1
kind: Secret
metadata:
  name: secret-test
data:
  username: "U2FuY2gtdHdvCg=="
  password: "Qm9oZGFuXyF1YmVyX3VudGVyX3ZhZmVsb2sxNDg4X2lnb3JfdG9saWsxNDg4Cg=="
---
apiVersion: kafkamanagement.instaclustr.com/v1beta1
kind: KafkaUser
metadata:
  name: kafkauser-sample
spec:
  secretRef:
    name: "secret-test"
    namespace: "default"
  initialPermissions: "standard"
  options:
    overrideExistingUser: true
    saslScramMechanism: "SCRAM-SHA-256"
