apiVersion: kafkamanagement.instaclustr.com/v1alpha1
kind: KafkaACL
metadata:
  labels:
    app.kubernetes.io/name: kafkaacl
    app.kubernetes.io/instance: kafkaacl-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: kafkaacl-sample
spec:
  acls:
      - host: "*"
        operation: DESCRIBE
        patternType: LITERAL
        permissionType: ALLOW
        principal: User:test
        resourceName: kafka-cluster
        resourceType: CLUSTER
  clusterId: c1af59c6-ba0e-4cc2-a0f3-65cee17a5f37
  id: c1af59c6-ba0e-4cc2-a0f3-65cee17a5f37_test
  userQuery: test

