apiVersion: v1
kind: Secret
metadata:
  name: secret-test
data:
  username: "U2FuY2gtdHdvCg=="
  password: "Qm9oZGFuX3ViZXJfdW50ZXJfaWdvcl90b2xpazEK"
---
apiVersion: kafkamanagement.instaclustr.com/v1beta1
kind: KafkaUser
metadata:
  name: kafkauser-sample
spec:
  secretRef:
    name: "secret-test"
    namespace: "default"
  initialPermissions: "standard"
  overrideExistingUser: true
  saslScramMechanism: "SCRAM-SHA-256"
  authMechanism: "SASL"
