apiVersion: v1
kind: Secret
metadata:
  name: secret-test
data:
  Username: "U2FuY2hv"
  Password: "ZnJlaGcxX3BpbmRmNTRfaW9rMDk="
---
apiVersion: kafkamanagement.instaclustr.com/v1alpha1
kind: KafkaUser
metadata:
  name: kafkauser-sample
spec:
  kafkaUserSecretName: "secret-test"
  kafkaUserSecretNamespace: "default"
  clusterId: "dcb8e03f-8bac-4f4b-83bc-34b6e7f3cb29"
  initialPermissions: "standard"
  options:
    overrideExistingUser: true
    saslScramMechanism: "SCRAM-SHA-512"
