apiVersion: kafkamanagement.instaclustr.com/v1beta1
kind: Mirror
metadata:
  name: mirror-sample
spec:
  kafkaConnectClusterId: "e01d85b5-5fce-4e68-be43-0bcd825b2baf"
  maxTasks: 3
  renameMirroredTopics: true
  sourceCluster:
    - alias: "source-cluster"
      managedCluster:
        - "sourceKafkaClusterId": "2a0b073d-b74a-4573-b6e5-45cef1b36eb2"
          "usePrivateIps": true
  "targetLatency": 5000
  "topicsRegex": ".*"
