apiVersion: kafkamanagement.instaclustr.com/v1beta1
kind: KafkaACL
metadata:
  name: kafkaacl-sample
spec:
  acls:
      - host: "*"
        operation: DESCRIBE
        patternType: LITERAL
        permissionType: ALLOW
        principal: User:test
        resourceName: kafka-cluster
        resourceType: CLUSTER
  clusterId: test
  userQuery: test
