apiVersion: clusters.instaclustr.com/v1beta1
kind: KafkaConnect
metadata:
  name: kafkaconnect-on-prem-sample
spec:
  name: "kafkaconnect-on-prem-sample"
  version: "3.5.1"
  privateNetworkCluster: false
  slaTier: "NON_PRODUCTION"
  targetCluster:
    - managedCluster:
        - targetKafkaClusterId: "377ebef6-f07c-4c59-b1da-feab2540568b"
          kafkaConnectVpcType: "SEPARATE_VPC"
  dataCentres:
    - name: "kafkaconnect-onprem"
      nodesNumber: 3
      cloudProvider: "ONPREMISES"
      replicationFactor: 3
      tags:
        tag: "oneTag"
        tag2: "twoTags"
      nodeSize: "KCN-DEV-OP.4.8-200"
      network: "10.15.0.0/16"
      region: "CLIENT_DC"
