apiVersion: clusters.instaclustr.com/v1beta1
kind: KafkaConnect
metadata:
  name: kafkaconnect-sample
spec:
  name: "kafkaconnect-onprem"
  version: "3.1.2"
  onPremisesSpec:
    storageClassName: managed-csi-premium
    osDiskSize: 20Gi
    dataDiskSize: 200Gi
    sshGatewayCPU: 2
    sshGatewayMemory: 4096Mi
    nodeCPU: 2
    nodeMemory: 8192Mi
    osImageURL: "https://s3.amazonaws.com/debian-bucket/debian-11-generic-amd64-20230601-1398.raw"
    cloudInitScriptRef:
      namespace: default
      name: instaclustr-cloud-init-secret
  privateNetworkCluster: false
  slaTier: "NON_PRODUCTION"
  targetCluster:
    - managedCluster:
        - targetKafkaClusterId: "34dfc53c-c8c1-4be8-bd2f-cfdb77ec7349"
          kafkaConnectVpcType: "KAFKA_VPC"
  dataCentres:
    - name: "kafkaconnect-onprem"
      nodesNumber: 3
      cloudProvider: "ONPREMISES"
      replicationFactor: 3
      tags:
        tag: "oneTag"
        tag2: "twoTags"
      nodeSize: "KCN-DEV-OP.4.8-200"
      network: "10.15.0.0/16"
      region: "CLIENT_DC"
