apiVersion: clusters.instaclustr.com/v1beta1
kind: Kafka
metadata:
  name: kafka-on-prem-sample
spec:
  name: "kafka-on-prem-sample"
  version: "3.3.1"
  pciCompliance: false
  replicationFactor: 3
  partitionsNumber: 3
  allowDeleteTopics: true
  autoCreateTopics: true
  clientToClusterEncryption: false
  privateNetworkCluster: false
  slaTier: "NON_PRODUCTION"
  dataCentres:
    - name: "onPremKafka"
      nodesNumber: 3
      cloudProvider: "ONPREMISES"
      tags:
        tag: "oneTag"
        tag2: "twoTags"
      nodeSize: "KFK-DEV-OP.4.8-200"
      network: "10.0.0.0/16"
      region: "CLIENT_DC"
  resizeSettings:
    - notifySupportContacts: false
      concurrency: 1