apiVersion: clusters.instaclustr.com/v1beta1
kind: PostgreSQL
metadata:
  name: postgresql-on-prem-sample
spec:
  name: "postgresql-on-prem-sample"
  version: "15.4.0"
  dataCentres:
    - region: "CLIENT_DC"
      network: "10.1.0.0/16"
      cloudProvider: "ONPREMISES"
      nodeSize: "PSQL-DEV-OP.4.8-200"
      nodesNumber: 2
      clientEncryption: false
      name: "testDC1"
      intraDataCentreReplication:
        - replicationMode: "SYNCHRONOUS"
      interDataCentreReplication:
        - isPrimaryDataCentre: true
  slaTier: "NON_PRODUCTION"
  privateNetworkCluster: false
  synchronousModeStrict: false