apiVersion: clusters.instaclustr.com/v1beta1
kind: Kafka
metadata:
  name: danylo-kafka
spec:
  name: "danylo-kafka"
  version: "3.3.1"
  pciCompliance: false
  replicationFactor: 3
  partitionsNumber: 3
  allowDeleteTopics: true
  autoCreateTopics: true
  clientToClusterEncryption: false
  privateNetworkCluster: false
  slaTier: "NON_PRODUCTION"
  onPremisesSpec:
    storageClassName: managed-csi-premium
    osDiskSize: 20Gi
    dataDiskSize: 200Gi
    sshGatewayCPU: 2
    sshGatewayMemory: 4096Mi
    nodeCPU: 2
    nodeMemory: 8192Mi
    osImageURL: "https://s3.amazonaws.com/debian-bucket/debian-11-generic-amd64-20230601-1398.raw"
    cloudInitScriptRef:
      namespace: default
      name: instaclustr-cloud-init-secret
  dataCentres:
    - name: "onPremKafka"
      nodesNumber: 3
      cloudProvider: "ONPREMISES"
      tags:
        tag: "oneTag"
        tag2: "twoTags"
      nodeSize: "KFK-DEV-OP.4.8-200"
      network: "10.0.0.0/16"
      region: "CLIENT_DC"
  resizeSettings:
    - notifySupportContacts: false
      concurrency: 1