apiVersion: clusters.instaclustr.com/v1beta1
kind: Redis
metadata:
  name: redis-on-prem-redis
spec:
  name: "redis-on-prem-redis"
  version: "7.0.14"
  slaTier: "NON_PRODUCTION"
  clientEncryption: false
  passwordAndUserAuth: true
  privateNetwork: false
  dataCentres:
    - region: "CLIENT_DC"
      name: "onPremRedis"
      cloudProvider: "ONPREMISES"
      network: "10.1.0.0/16"
      nodeSize: "RDS-PRD-OP.8.64-400"
      masterNodes: 3
      replicationFactor: 0