apiVersion: clusters.instaclustr.com/v1beta1
kind: Cassandra
metadata:
  name: cassandra-on-prem-sample
spec:
  name: "cassandra-on-prem-sample"
  version: "4.1.3"
  privateNetwork: true
  dataCentres:
    - name: "onPremCassandra"
      region: "CLIENT_DC"
      cloudProvider: "ONPREMISES"
      continuousBackup: false
      nodesNumber: 2
      replicationFactor: 2
      privateIpBroadcastForDiscovery: true
      network: "192.168.0.0/16"
      tags:
        "onprem": "test"
      clientToClusterEncryption: true
      nodeSize: "CAS-PRD-OP.4.8-200"
  passwordAndUserAuth: true
  slaTier: "NON_PRODUCTION"
