apiVersion: clusters.instaclustr.com/v1beta1
kind: Cadence
metadata:
  name: cadence-sample
spec:
  name: "cadence-test"
  version: "1.0.0"
  onPremisesSpec:
    storageClassName: managed-csi-premium
    osDiskSize: 20Gi
    dataDiskSize: 200Gi
    sshGatewayCPU: 2
    sshGatewayMemory: 4096Mi
    nodeCPU: 2
    nodeMemory: 8192Mi
    osImageURL: "https://s3.amazonaws.com/debian-bucket/debian-11-generic-amd64-20230601-1398.raw"
    cloudInitScriptRef:
      namespace: default
      name: instaclustr-cloud-init-secret
  standardProvisioning:
    - targetCassandra:
        dependencyCdcId: "9d43ac54-7317-4ce5-859a-e9d0443508a4"
        dependencyVpcType: "TARGET_VPC"
  privateNetworkCluster: false
  dataCentres:
    - region: "CLIENT_DC"
      network: "10.1.0.0/16"
      cloudProvider: "ONPREMISES"
      name: "testdc"
      nodeSize: "CAD-DEV-OP.4.8-200"
      nodesNumber: 2
      clientEncryption: false
  slaTier: "NON_PRODUCTION"
  useCadenceWebAuth: false