apiVersion: v1
kind: Secret
metadata:
  name: creds-secret
  namespace: system
type: Opaque
data:
  USERNAME: $USERNAME
  APIKEY: $APIKEY
  HOSTNAME: $HOSTNAME
  CASSANDRA_DATA_VOLUME_IMAGE_URL: $CASSANDRA_DATA_VOLUME_IMAGE_URL
