# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/clusters.instaclustr.com_cassandras.yaml
- bases/clusters.instaclustr.com_postgresqls.yaml
- bases/clusters.instaclustr.com_opensearches.yaml
- bases/clusterresources.instaclustr.com_awsvpcpeerings.yaml
- bases/clusters.instaclustr.com_redis.yaml
- bases/clusters.instaclustr.com_cadences.yaml
- bases/clusters.instaclustr.com_kafkas.yaml
- bases/clusterresources.instaclustr.com_azurevnetpeerings.yaml
- bases/clusterresources.instaclustr.com_gcpvpcpeerings.yaml
- bases/clusters.instaclustr.com_kafkaconnects.yaml
- bases/clusterresources.instaclustr.com_clusternetworkfirewallrules.yaml
- bases/clusterresources.instaclustr.com_awssecuritygroupfirewallrules.yaml
- bases/kafkamanagement.instaclustr.com_topics.yaml
- bases/clusterresources.instaclustr.com_maintenanceevents.yaml
- bases/clusters.instaclustr.com_zookeepers.yaml
- bases/kafkamanagement.instaclustr.com_kafkausers.yaml
- bases/kafkamanagement.instaclustr.com_mirrors.yaml
- bases/clusterresources.instaclustr.com_clusterbackups.yaml
- bases/clusterresources.instaclustr.com_nodereloads.yaml
- bases/kafkamanagement.instaclustr.com_kafkaacls.yaml
- bases/clusterresources.instaclustr.com_redisusers.yaml
- bases/clusterresources.instaclustr.com_awsencryptionkeys.yaml
- bases/clusterresources.instaclustr.com_cassandrausers.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_cassandras.yaml
#- patches/webhook_in_postgresqls.yaml
#- patches/webhook_in_opensearches.yaml
#- patches/webhook_in_awsvpcpeerings.yaml
#- patches/webhook_in_redis.yaml
#- patches/webhook_in_cadences.yaml
#- patches/webhook_in_kafkas.yaml
#- patches/webhook_in_azurevnetpeerings.yaml
#- patches/webhook_in_gcpvpcpeerings.yaml
#- patches/webhook_in_kafkaconnects.yaml
#- patches/webhook_in_clusternetworkfirewallrules.yaml
#- patches/webhook_in_kafkausers.yaml
#- patches/webhook_in_awssecuritygroupfirewallrules.yaml
#- patches/webhook_in_topics.yaml
#- patches/webhook_in_maintenanceevents.yaml
#- patches/webhook_in_zookeepers.yaml
#- patches/webhook_in_nodereloads.yaml
#- patches/webhook_in_mirrors.yaml
#- patches/webhook_in_kafkaacls.yaml
#- patches/webhook_in_redisusers.yaml
#- patches/webhook_in_awsencryptionkeys.yaml
#- patches/webhook_in_cassandrausers.yaml
#- patches/webhook_in_clusterbackups.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_cassandras.yaml
- patches/cainjection_in_clusters_postgresqls.yaml
- patches/cainjection_in_clusters_opensearches.yaml
#- patches/cainjection_in_awsvpcpeerings.yaml
#- patches/cainjection_in_redis.yaml
#- patches/cainjection_in_cadences.yaml
#- patches/cainjection_in_kafkas.yaml
#- patches/cainjection_in_azurevnetpeerings.yaml
#- patches/cainjection_in_gcpvpcpeerings.yaml
#- patches/cainjection_in_kafkaconnects.yaml
#- patches/cainjection_in_clusternetworkfirewallrules.yaml
#- patches/cainjection_in_kafkausers.yaml
#- patches/cainjection_in_awssecuritygroupfirewallrules.yaml
#- patches/cainjection_in_topics.yaml
- patches/cainjection_in_clusterresources_maintenanceevents.yaml
#- patches/cainjection_in_zookeepers.yaml
#- patches/cainjection_in_nodereloads.yaml
#- patches/cainjection_in_mirrors.yaml
#- patches/cainjection_in_kafkaacls.yaml
#- patches/cainjection_in_redisusers.yaml
#- patches/cainjection_in_awsencryptionkeys.yaml
#- patches/cainjection_in_cassandrausers.yaml
#- patches/cainjection_in_cassandras.yaml
#- patches/cainjection_in_opensearches.yaml
#- patches/cainjection_in_postgresqls.yaml
#- patches/cainjection_in_clusterbackups.yaml
#- patches/cainjection_in_maintenanceevents.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
