apiVersion: clusters.instaclustr.com/v1alpha1
kind: Kafka
metadata:
  name: kafka
spec:
  name: "kafka"
  version: "2.8.2"
  pciCompliance: false
  replicationFactorNumber: 3
  partitionsNumber: 3
  allowDeleteTopics: true
  autoCreateTopics: true
  clientToClusterEncryption: true
  privateNetworkCluster: true
  slaTier: "NON_PRODUCTION"
  dataCentres:
    - name: "AWS_VPC_US_EAST_1"
      nodesNumber: 3
      cloudProvider: "AWS_VPC"
      tags:
        tag: "oneTag"
        tag2: "twoTags"
      nodeSize: "KFK-DEV-t4g.small-5"
      network: "10.0.0.0/16"
      region: "US_EAST_1"
