apiVersion: clusters.instaclustr.com/v1beta1
kind: OpenSearch
metadata:
  name: opensearch
  namespace: default
  annotations:
    defaulter: webhook
spec:
  alertingPlugin: false
  bundledUseOnly: false
  anomalyDetectionPlugin: false
  asynchronousSearchPlugin: false
#  twoFactorDelete:
#    - email: "emailTEST"
#      phone: "phoneTEST"
#  userRef:
#    name: test-user
#    namespace: default
  clusterManagerNodes:
    - dedicatedManager: true
      nodeSize: SRH-DEV-t4g.small-5
  dataCentres:
    - cloudProvider: AWS_VPC
      name: AWS_VPC_US_EAST_1
      network: 10.0.0.0/16
      numberOfRacks: 3
      privateLink: false
      region: US_EAST_1
      accountName: "Custom"
      awsSettings:
        - diskEncryptionKey: "123e4567-e89b-12d3-a456-426614174000"
      tags:
        tag: "oneTag"
        tag2: "twoTags"
  resizeSettings:
    - concurrency: 1
  ingestNodes:
     - nodeSize: SRH-DI-PRD-m6g.large-10
       nodeCount: 3
  dataNodes:
    - nodesNumber: 3
      nodeSize: SRH-DEV-t4g.small-5
  icuPlugin: false
  indexManagementPlugin: true
  knnPlugin: false
  loadBalancer: false
  name: operatorOpenSearch
  notificationsPlugin: false
#  opensearchDashboards:
#    - nodeSize: SRH-DEV-t4g.small-5
#      oidcProvider: ''
#      version: opensearch-dashboards:2.5.0
  version: 1.0.0
  pciCompliance: false
  privateNetwork: true
  reportingPlugin: false
  slaTier: NON_PRODUCTION
  sqlPlugin: false
