apiVersion: clusters.instaclustr.com/v1beta1
kind: PostgreSQL
metadata:
  name: postgresql-sample
  annotations:
    testAnnotation: test
spec:
  name: "testPostgre"
  clusterConfigurations:
    idle_in_transaction_session_timeout: "1"
  version: "14.5.0"
  dataCentres:
    - region: "US_EAST_1"
      network: "10.1.0.0/16"
      cloudProvider: "AWS_VPC"
      nodeSize: "PGS-DEV-t4g.small-5"
      nodesNumber: 2
      accountName: "accountNameTEST"
#      cloudProviderSettings:
#        - customVirtualNetworkId: "vpc-12345678"
#          diskEncryptionKey: "123e4567-e89b-12d3-a456-426614174000"
#          resourceGroup: "asdfadfsdfas"
      clientEncryption: true
      name: "testDC1"
      pgBouncer:
        - pgBouncerVersion: "pgBouncerVersionTest"
          poolMode: "poolModeTest"
      intraDataCentreReplication:
        - replicationMode: "SYNCHRONOUS"
      interDataCentreReplication:
        - isPrimaryDataCentre: true
  slaTier: "NON_PRODUCTION"
  privateNetworkCluster: true
  synchronousModeStrict: true
#  twoFactorDelete:
#    - email: "emailTEST"
#      phone: "phoneTEST"
