apiVersion: clusters.instaclustr.com/v1beta1
kind: Redis
metadata:
  name: redis-sample
  namespace: default
  annotations:
    defaulter: webhook
spec:
  name: "testRedis"
  version: "7.0.5"
  slaTier: "NON_PRODUCTION"
  pciCompliance: true
  clientToNodeEncryption: true
  privateNetworkCluster: true
  notifySupportContacts: true
#  twoFactorDelete:
#    - email: "emailTEST"
#      phone: "phoneTEST"
  clientEncryption: true
  passwordAndUserAuth: true
  dataCentres:
    - region: "US_WEST_2"
      cloudProvider: "AWS_VPC"
      network: "10.1.0.0/16"
      nodeSize: "t3.small-20-r"
      masterNodes: 3
      nodesNumber: 3
      name: "testDC2"
#      accountName: "Custrom"
#      awsSettings:
#        - customVirtualNetworkId: "vpc-12345678"
#          diskEncryptionKey: "123e4567-e89b-12d3-a456-426614174000"
