apiVersion: clusters.instaclustr.com/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper-sample
  namespace: default
  annotations:
    defaulter: webhook
spec:
  dataCentres:
    - clientToServerEncryption: true
      cloudProvider: "AWS_VPC"
      name: "MyTestDataCentre1"
      network: "10.0.0.0/16"
      nodeSize: "zookeeper-developer-t3.small-20"
      nodesNumber: 3
      region: "US_EAST_1"
#      accountName: "Custrom"
#      cloudProviderSettings:
#        - customVirtualNetworkId: "vpc-12345678"
#          diskEncryptionKey: "123e4567-e89b-12d3-a456-426614174000"
#          resourceGroup: "asdfadfsdfas"
  name: "bohdan-zookeeper-test"
  privateNetwork: true
#  twoFactorDelete:
#    - email: "emailTEST"
#      phone: "phoneTEST"
  slaTier: "NON_PRODUCTION"
  version: "3.6.3"
