name: pre-main-instaclustr-operator-ci-cd

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  pre-main-operator-build-and-push:
    name: PRE-MAIN Build and push the Instaclustr Operator
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Lint Go code
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
          golangci-lint run --timeout 5m --skip-dirs=pkg/instaclustr/mock

      - name: Check goimports
        uses: Jerome1337/goimports-action@v1.0.3
        with:
          goimports-path: './'

      - name: Test Go code
        run: |
          sudo apt update
          sudo apt-get install -y make
          make test
