name: pre-main-instaclustr-operator-ci-cd

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  pre-main-operator-build-and-push:
    name: PRE-MAIN Build and push the Instaclustr Operator
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Lint Go code
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
          golangci-lint run --timeout 5m --skip-dirs=pkg/instaclustr/mock

      - name: Make goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@v0.5.0
          files_to_be_goimported=$(find . -type f -name '*.go' -not -path "./vendor/*")
          goimports -v -w -local ./ -l $files_to_be_goimported

      - name: Test Go code
        run: |
          sudo apt update
          sudo apt-get install -y make
          make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Operator image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/instacluster-operator:io-${{ github.run_id }}-${{ github.run_attempt }}
